### ISSUE TITLE
Move RequiresApi calls to @file use site for types introduced after API 14.

### ISSUE THREAD

**Issue by JakeWharton** [android/android-ktx#113]
Blocked by https://issuetracker.google.com/issues/72509076

**Comment by Androbin** [comment]
Blocker was marked as "Fixed" on Feb 7.

**Comment by JakeWharton** [comment]
Fixed is not released.

**Comment by Androbin** [comment]
Oops, my fault.

**Comment by JakeWharton** [comment]
This creates a problem for API tracking with metalava and I don't think it's a big hassle anyway so just going to close.
