### ISSUE TITLE
Provide a way to obtain a not null Context from a Fragment

### ISSUE THREAD

**Issue by quiro91** [android/android-ktx#134]
Support Library 27 made `Fragment.getContext()` and `Fragment.getActivity()` nullable. In order to provide a better API to be consumed in Kotlin, I'd consider creating something like `Fragment.getContextOrThrow()`, similarly with the already created TypedArray extension functions

**Comment by JakeWharton** [comment]
This library does not cover support library APIs.

**Comment by JakeWharton** [comment]
Moreover, just wait until the next support library release and your wish might magically be granted.
