### ISSUE TITLE
Visibility extensions for View classes

### ISSUE THREAD

**Issue by kostya17** [android/android-ktx#135]
I'm considering adding a few methods to View class in order to set visibility, like: 
```
setVisible()
setInvisible()
setGone()
```
(API is a subject to change if you will)
What do you think guys? Is it something we would like to see in android-ktx?

**Comment by rock3r** [comment]
I sometimes add and use `isVisible`/`isInvisible`/`isGone` too

**Comment by abbath0767** [comment]
https://github.com/android/android-ktx/pull/137 - is first feature what i make in kotlin and use still now. I think they have almost every project and then they just have to be)

**Comment by ouattararomuald** [comment]
Personally I use `show()` and `hide()` respectively for `visibility = View.VISIBLE` and `visibility = View.INVISIBLE`. For `View.GONE` what comes to my mind is `gone()` or `disappear()`.

**Comment by chrisbanes** [comment]
@ouattararomuald You're in for a bad time with `show()` and `hide()` on FloatingActionButton.

**Comment by AkshayChordiya** [comment]
We can have: 

```
fun View.visible() {
    visibility = View.VISIBLE
}

fun View.invisible() {
    visibility = View.INVISIBLE
}

fun View.gone() {
    visibility = View.GONE
}
```

If these look good then I can make a PR.

**Comment by romainguy** [comment]
There is already a pending PR for these

**Comment by abbath0767** [comment]
Here https://github.com/android/android-ktx/pull/146 variant of @ouattararomuald. I use the same naming for current extensions

**Comment by ouattararomuald** [comment]
@chrisbanes Thanks for pointing this out

**Comment by JakeWharton** [comment]
Here's my take: https://github.com/android/android-ktx/compare/jakew/visibility-properties/2018-02-06

I'm not really a fan of the function approach to setting this state because it makes the code more verbose when dealing with booleans from a model or other conditional logic.

**Comment by romainguy** [comment]
@JakeWharton I like this property based approach. It also solves the naming problem with `gone`.

**Comment by chrisbanes** [comment]
+1 to properties.

**Comment by tiembo** [comment]
👍 for properties

**Comment by abbath0767** [comment]
Oh, i pushed new commit with solved problems after review from @JakeWharton. But i see new nice idea - change 6 functions to 3 properties. And i see what community likes the idea...
