### ISSUE TITLE
Add an extension property to get the children of a ViewGroup as a Iterable

### ISSUE THREAD

**Issue by quiro91** [android/android-ktx#138]
```kotlin
val ViewGroup.children: Iterable<View>
    get() = (0 until childCount).map { getChildAt(it) }
```

This would enable to use all the operators from the Kotlin standard library like filter and so on instead of having to rewrite them all as ViewGroup extension functions

**Comment by JakeWharton** [comment]
Yeah we used to have something like this until we switched to `operator fun iterator()`. It's a shame there isn't a structural typing such that all the existing collection extensions could apply. Is there any reason to expose a `List` rather than an `Iterable`?

**Comment by quiro91** [comment]
Honestly no, I agree that `Iterable` seems more appropriate. Will change the title of the issue

**Comment by kevinmost** [comment]
Any thoughts on it being a `Sequence` instead? This is what we implemented in our project, I'm not sure if the laziness of a sequence is more or less desirable though.

```kotlin
/**
 * Returns a [Sequence] that iterates through the children of this view
 */
val ViewGroup.children: Sequence<View>
    get() {
        var currentIndex = -1
        return generateSequence {
            currentIndex++
            getChildAt(currentIndex)
        }
    }
```

**Comment by mokkun** [comment]
IMHO it should always return a `Iterable`. If you need it as a sequence you could always do `myView.children.asSequence()`.

**Comment by JakeWharton** [comment]
The opposite of that is also true in asIterable()

**Comment by JakeWharton** [comment]
Yeah. Plus there actually are a few eager operators on Sequence like `any`
which are commonly used.

**Comment by JakeWharton** [comment]
Was merged.
