### ISSUE TITLE
`Toast` extensions on `Context`

### ISSUE THREAD

**Issue by n8ebel** [android/android-ktx#143]
I've seemed to add this to each Kotlin project I've worked on

`fun Context.shortToast(msg: CharSequence) = Toast.makeText(this, msg, Toast.LENGTH_SHORT).show()`

`fun Context.longToast(msg: CharSequence) = Toast.makeText(this, msg, Toast.LENGTH_LONG).show()`

cleans up the api a bit and avoids the need to remember to call `show()`

**Comment by egor-n** [comment]
This may be handy, but apps should really stop using `Toast` since they don't show up if notifications are disabled for an app.

**Comment by bernaferrari** [comment]
Egor, I'm curious, what is the recommended way? Snackbar?

**Comment by MGaetan89** [comment]
And instead of two methods, why not one with a `duration` parameter?

**Comment by abbath0767** [comment]
i thing good solution for duration is default fun argument, like this:
```
fun Context.toast(messageId: Int, duration: Int = Toast.LENGTH_LONG) =
        Toast.makeText(this, messageId, duration).show()
```

**Comment by n8ebel** [comment]
a single function with a duration arg & a default value is a nice idea 👍    whether it's added here or not, I'll have to incorporate that 😄

**Comment by jshvarts** [comment]
I normally something similar to what @abbath0767 suggested. 
    fun Context.toast(@StringRes resId: Int, duration: Int = Toast.LENGTH_LONG) =
        Toast.makeText(this, resId, duration).show()

**Comment by JakeWharton** [comment]
> avoids the need to remember to call `show()`

Lint guards against this.

**Comment by frederickcxa** [comment]
What about this?

```
fun Context.toast(content: Any, length: Int = Toast.LENGTH_SHORT): Toast {
    val message = when (content) {
        is String -> content
        is Int -> getString(content)
        else -> throw IllegalArgumentException("Content must be a String or a String resource id.")
    }

    return Toast.makeText(this, message, length).also { it.show() }
}
```

Here we can pass a `String`|`String resource id` to the method, also we return the toast object back to the caller. 😃

**Comment by JakeWharton** [comment]
That seems like it sacrifices type safety for no benefit whatsoever. Why wouldn't you use an overload?

**Comment by frederickcxa** [comment]
You right, type safety for the win.

**Comment by frederickcxa** [comment]
We could use `also` to be able to show and return the `Toast`.

```
fun Context.toast(@StringRes resId: Int, duration: Int = Toast.LENGTH_LONG) =
    Toast.makeText(this, resId, duration).also { it.show() }
```

This gives more flexibility to the API users. 😃

**Comment by mitrejcevski** [comment]
IMO the toast should not be an extension of `Context`, but an `Activity`. The reason is that the `Context` might not be an Activity context, and some devices (i.e. Samsung, Xaomi) would complain. I've seen that happening recently.

**Comment by avaytsekhovskiy** [comment]
I do believe that `.apply { show() }` should be part of this extension. Even lint thinks that toast should be created to be shown :) 

That's how i use it in projects:
```kotlin
 fun Context.toast(message: CharSequence, duration: Int = Toast.LENGTH_SHORT): Toast =
        Toast.makeText(this, message, duration).apply { show() }
```

toasts are great for visual debugging, not for end user. So i prefer LENGTH_SHORT as default value. What do you think?

**Comment by MGaetan89** [comment]
What's the advantage(s) of using `also`/`apply` instead of directly `show`?

**Comment by avaytsekhovskiy** [comment]
@MGaetan89 to return `toast` object as the result. `show()` returns Unit, unlike `Context.toast()` will return created toast instance.

**Comment by MGaetan89** [comment]
@avaytsekhovskiy oh right, I didn't noticed that it became the method's body. Thanks

**Comment by simonschiller** [comment]
I always assumed it was better to create a `Toast` using the `ApplicationContext` (see: https://stackoverflow.com/questions/46730738/toast-maketext-activity-or-application-context).

So I would suggest doing something like this:
```
fun Context.toast(text: CharSequence, duration: Int = Toast.LENGTH_SHORT): Toast =
        Toast.makeText(this.applicationContext, text, duration).apply { show() }
```

This would also answer the proposal of @mitrejcevski

**Comment by jshvarts** [comment]
@MGaetan89 returning a Toast will give an opportunity for the caller to hide the `Toast` before time is up by calling `toast.cancel()`

**Comment by illuzor** [comment]
@simonschiller maybe like this:

```
fun Context.toast(text: CharSequence, long: Boolean = false): Toast =
        Toast.makeText(this.applicationContext, text, if (long) Toast.LENGTH_LONG else Toast.LENGTH_SHORT).apply { show() }
```

**Comment by simonschiller** [comment]
@illuzor I would argue that a duration parameter is better than a boolean flag, as `toast("Lorem Ipsum", Toast.LENGTH_SHORT)` is more readable than `toast("Lorem Ipsum", false)`

**Comment by JakeWharton** [comment]
Was merged.

**Comment by jemshit** [comment]
Hi, is toast extension removed, can't import it using version `1.0.0-rc02`?

**Comment by JakeWharton** [comment]
Yes

**Comment by hacker1024** [comment]
> Yes

Why?
