### ISSUE TITLE
Feature suggestion : Adding Life-Cycle aware variables extensions

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [android/android-ktx#152]
I have made a library that makes it possible to make variables Life-Cycle aware, so instead of creating a new class that implements LifeCycleObserver and add my code in the corresponding methods, I just hold on to the Variable and pass functions that will be executed upon the variable when a Life-Cycle event happens, the library is called LiteCycle : 

https://github.com/Ahmed-Adel-Ismail/LiteCycle

And sample code for this LiteCycle is as follows  :

// handling RxJava 2 Disposables
LiteCycle.with(titleText.subscribe(titleTextView::setText))
                .forLifeCycle(this)
                .onDestroyInvoke(Disposable::dispose)
                .observe();

// handling normal values
LiteCycle.with(10)
        .forLifeCycle(this)
        .onCreateInvoke(i -> Log.e("LiteCycle", "initial value " + i))
        .onCreateUpdate(i -> i + 1)
        .onCreateInvoke(i -> Log.e("LiteCycle", "onCreate() invoked " + i))
        .onStartUpdate(i -> i + 1)
        .onStartInvoke(i -> Log.e("LiteCycle", "onStart() invoked " + i))
        .onResumeUpdate(i -> i + 1)
        .onResumeInvoke(i -> Log.e("LiteCycle", "onResume() invoked " + i))
        .onPauseUpdate(i -> i + 1)
        .onPauseInvoke(i -> Log.e("LiteCycle", "onPause() invoked " + i))
        .onStopUpdate(i -> i + 1)
        .onStartInvoke(i -> Log.e("LiteCycle", "onStop() invoked " + i))
        .onDestroyUpdate(i -> 10)
        .onDestroyInvoke(i -> Log.e("LiteCycle", "onDestroy() invoked " + i))
        .onFinishingUpdate(i -> null)
        .onFinishingInvoke(i -> Log.e("LiteCycle", "isFinishing() invoked " + i))
        .observe();

// listening to the changes done during the life cycle
Observable<Integer> integer = LiteCycle.with(10)
        .forLifeCycle(this)
        .onCreateUpdate(i -> i + 1)
        .onStartUpdate(i -> i + 1)
        .onResumeUpdate(i -> i + 1)
        .onPauseUpdate(i -> i + 1)
        .onStopUpdate(i -> i + 1)
        .onDestroyUpdate(i -> 10)
        .observe();
        
Disposable disposable = integer.subscribe(i -> Log.e("LiteCycle", "integer value " + i));

I was thinking about adding this as an extension function to Any object, like as follows : 

_**10**.forLifeCycle(this)
        .onCreateInvoke(i -> Log.e("LiteCycle", "initial value " + i))
        .observe();_

and within this extension function, we make it as follows : 

```
fun <T> T.forLifeCycle (lifeCycleOwner : LifeCycleOwner) : LiteObserverBuilder<T,*,*> = 
        LiteCycle.with(this).forLifeCycle(lifeCycleOwner)
```

**Comment by JakeWharton** [comment]
This requires a base class or a dependency on lifecycle extensions and we are not interested in the former and cannot depend on the latter in this library. So an external library is best.
