### ISSUE TITLE
Extension for fragment transaction

### ISSUE THREAD

**Issue by jitinsharma** [android/android-ktx#156]
An extension on AppCompatActivity
```
inline fun AppCompatActivity.transact(action: FragmentTransaction.() -> Unit) {
    supportFragmentManager.beginTransaction().apply {
        action()
    }.commit()
}
```

Inside activity
```
transact {
    replace(R.id.container, fragment)
    setCustomAnimations(R.anim.abc_fade_in, R.anim.abc_fade_out)
}
```

This will not directly work for fragment. We may create another extension for fragment or create an extension on Fragment manager.

**Comment by romainguy** [comment]
This library does not cover support library APIs.

**Comment by arekolek** [comment]
@jitinsharma looks like it's now in `androidx.fragment:fragment-ktx` artifact:

https://developer.android.com/kotlin/ktx#examples

![image](https://user-images.githubusercontent.com/893533/41161480-4fdb3cce-6b33-11e8-8b23-0bbc3f3c43e9.png)

But I guess one has to migrate to AndroidX to use it

**Comment by ultraon** [comment]
Where I can see the source code for all ktx extensions (not only core)?

**Comment by JakeWharton** [comment]
Link at the top of the README

**Comment by ultraon** [comment]
Thanks Jake, I found it, a little bit strange structure of dirs for ktx extensions, it would be great to have some list with urls for all ktx extensions (source code).
