### ISSUE TITLE
Feature suggestion: simplified factory for ViewModel

### ISSUE THREAD

**Issue by piotrek-chmielowski** [android/android-ktx#157]
In order to use constructor injection on the `ViewModel`, we have to create a `ViewModelProvider.Factory` implementation, take dependencies as constructor parameter and pass them to the `ViewModel` constructor:

```
class ViewModelFactory @Inject constructor(val dependency: Dependency) :
    ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>) =
        when (modelClass) {
            TaskListViewModel::class -> MyViewModel(dependency) as T
            else -> throw Error("Bad type")
        }
}
```

However, sometimes it is more convenient to have the factory generated for us (for example by using [AutoFactory](https://github.com/google/auto/tree/master/factory)). Then, the implementation of `ViewModelProvider.Factory` becomes just a boilerplate which takes the generated factory object as constructor parameter and just call its `create()` method.

In such case, to reduce the amount of code, we can inline this class:

```
ViewModelProviders.of(this, object : ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>) = 
        viewModelFactory.create() as T
}).get(MainViewModel::class.java)
```

It looks ugly, so let's introduce `SimpleFactory` class (**and this is my feature proposal**):

```
class SimpleFactory<out T : ViewModel?>(val factory: () -> T) :
    ViewModelProvider.Factory {
    override fun <T : ViewModel?> create(modelClass: Class<T>) =
        factory() as T
}
```
And now, the previous snippet could be simplified to following one:
```
ViewModelProviders.of(this, SimpleFactory { viewModelFactory.create() })
    .get(MainViewModel::class.java)
```

A real life example:
```
class MainActivity : AppCompatActivity() {

    @Inject
    lateinit var viewModelFactory: MainViewModelFactory // One generated by AutoFactory

    private val viewModel by lazy {
        ViewModelProviders.of(this, SimpleFactory { viewModelFactory.create() })
            .get(MainViewModel::class.java)
    }

    // rest of the activity code...
}
```

What do you think?

**Comment by JakeWharton** [comment]
This library does not cover support library APIs. Only the platform. We have something like this coming soon though!
