### ISSUE TITLE
Extension for Network connectivity check

### ISSUE THREAD

**Issue by jitinsharma** [android/android-ktx#160]
This may seem specific but almost every project which does network call would be using this.

```
@RequiresPermission(value = Manifest.permission.ACCESS_NETWORK_STATE)
fun Context.isConnected(): Boolean {
    val connectivityManager = this
            .getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager
    connectivityManager?.let {
        val netInfo = it.activeNetworkInfo
        netInfo?.let {
            if (it.isConnected) return true
        }
    }
    return false
}
```

**Comment by JakeWharton** [comment]
I do find this very specific, yes, and I'm struggling to justify such an extension on such a visible type. This would set a precedent for adding hundreds of extensions as convenience accessors onto context which would be difficult to maintain and would make it hard to say "no" in the future. Beyond that, the primary goal of this library is to add extensions which enable Kotlin-specific language features and helpers and not just moving access to existing things.

**Comment by jitinsharma** [comment]
Ok.

**Comment by tobiasschuerg** [comment]
Would also prefer an `isOnline()` function or similar to be in as this is something I'm having to add to any project anyways.
