### ISSUE TITLE
Shared preferences

### ISSUE THREAD

**Issue by jermainedilao** [android/android-ktx#170]
Make **action** return SharedPreferences.Editor instead of Unit so the method body could be converted to single line

`inline fun SharedPreferences.edit(action: SharedPreferences.Editor.() -> SharedPreferences.Editor) = edit().action().apply()`

**Comment by JakeWharton** [comment]
A single line already works:
```kotlin
preferences.edit { putString("key", "value") }
```
Please provide a failing snippet if you think something isn't working correctly.

**Comment by jermainedilao** [comment]
Sorry. Everything is working correctly for SharedPreferences, but I only mean the lesser lines of code for the method definition itself though.

**Comment by JakeWharton** [comment]
Implementation size is not a priority.
