### ISSUE TITLE
Other components than Extensions functions?

### ISSUE THREAD

**Issue by galex** [android/android-ktx#173]
Hi,
 
Are other components also welcomed in android-ktx like a [property delegate class for SharedPreferences](https://gist.github.com/galex/ef830ae36f3c44f272776fce8fd78a19) or helper classes like the [SingletonHolder ](https://medium.com/@BladeCoder/kotlin-singletons-with-argument-194ef06edd9e) which are super useful (and I find myself adding those to each of my projects)?

**Comment by AlexeyGorovoy** [comment]
I believe KTX stands for "kotlin extensions" therefore it would be wrong to add other types of functionality. But of course, I'm just a passerby and not really liable to answer your question.

**Comment by romainguy** [comment]
The goal of android-ktx is to not add features, but just simplify existing APIs.
