### ISSUE TITLE
Inflater extensions for Context

### ISSUE THREAD

**Issue by avaytsekhovskiy** [android/android-ktx#175]
It would be great to simplify view inflating by property:
```kotlin
val Context.inflater: LayoutInflater get() = LayoutInflater.from(this)
```
 
___
Also it may be useful to extend ViewGroup with inflate():

```kotlin
fun ViewGroup.inflate(@LayoutRes resId: Int, attachToRoot: Boolean = false): View =
        context.inflater.inflate(resId, this, attachToRoot)
```

So that RecyclerView.Adapter.onCreateViewHolder() may look simplier

```kotlin
return new ViewHolder(parent.inflate(R.layout.item))
```

or if you're building hierarchy

```kotlin
parent.apply {
    inflate(R.layout.item1, true)
    inflate(R.layout.item2, true)
}
```

**Comment by AlexeyGorovoy** [comment]
Great idea with `ViewGroup.inflate()` function! We use in our projects too and happy with that 👍

**Comment by MGaetan89** [comment]
`ViewGroup.inflate()` is proposed in #162
