### ISSUE TITLE
For System Services

### ISSUE THREAD

**Issue by yongjhih** [android/android-ktx#178]
Before:

```java
NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
```

After:

```kt
val notificationManager = context.getNotificationManager()
```

ref. https://github.com/yongjhih/kotlin-extensions/blob/master/kotlinx-android-system-services/src/main/kotlin/kotlinx/android/system/services/SystemServicesExt.kt

**Comment by paour** [comment]
It's [implemented](https://github.com/android/android-ktx/blob/master/src/main/java/androidx/content/Context.kt#L37) as `Context.getSystemService()`.

**Comment by romainguy** [comment]
As paour mentionned, it's already implemented.
