### ISSUE TITLE
For View animations such like View.fadeIn(ms) and View.fadeOut(ms)

### ISSUE THREAD

**Issue by yongjhih** [android/android-ktx#179]
* `View.fadeIn(ms)`
* `View.fadeOut(ms)`
* `View.translateX(ms)`
* `View.translateY(ms)`
* etc.

Advanced:
* `View.fadeIn(ms, onStart, onEnd)`

**Comment by romainguy** [comment]
This is not a huge win compared to the ViewPropertyAnimator and it would make the animations too specific (`fadIn` and `fadeOut` could work though).

**Comment by JakeWharton** [comment]
Yeah I'm not really sold on the wide-spread applicability of such things. Mostly because as soon as you start customizing you're forced to completely change the mechanism of animation here from a helper method to VPA.
