### ISSUE TITLE
 Lifecycle aware AsyncTask wrapper

### ISSUE THREAD

**Issue by ErikHellman** [android/android-ktx#181]
I made an extension function on `LifecycleOwner` that wraps an `AsyncTask` that gets automatically cancelled at `onDestroy()`. Could this be something for this library?

See https://github.com/ErikHellman/android-ktx/blob/feature/lifecycle_aware_asynctask/src/main/java/androidx/arch/lifecycle/LifecycleOwner.kt

Example of usage;
```
load { 
    val result = expensiveNetworkOperation()
} then {
    val textView = findViewById(R.id.myResult)
    textView.text = it
}
```

**Comment by MGaetan89** [comment]
The Architecture Component is not in the scope of this projet.

**Comment by ErikHellman** [comment]
Cool. I missed that part. :)

**Comment by romainguy** [comment]
Indeed, this is only for Framework APIs
