### ISSUE TITLE
Tinting

### ISSUE THREAD

**Issue by johanneslaubermoovel** [android/android-ktx#183]
Make tinting views easier:

Before:
`view.imageTintList = ContextCompat.getColorStateList(context!!, myColor) }`

After:
`view.tint(myColor)`

Implementation:
```
fun View.tint(myColor: Int) {
       ContextCompat.getColorStateList(context, myColor) }
}
```

**Comment by romainguy** [comment]
android-ktx is for the framework only, not for support library.

**Comment by AOrobator** [comment]
@romainguy Are there plans to have a similar project for the support library? Most developers using the Android framework are also using the Support library, so extensions would be much appreciated for both.
