### ISSUE TITLE
JakeWharton.Kotterknife

### ISSUE THREAD

**Issue by daberni** [android/android-ktx#184]
Any plans of including your "kotterknife" view binding delegations?

https://github.com/JakeWharton/kotterknife

I am very happy with those, at least for activities. Although they are not perfect for Fragments at the moment.

**Comment by Edward608** [comment]
Dupe of #172

**Comment by jeksor** [comment]
Why are you need it?
Just use the synthetic, what's it)
https://kotlinlang.org/docs/tutorials/android-plugin.html

**Comment by JakeWharton** [comment]
Nope
