### ISSUE TITLE
Custom Recycler Adapter

### ISSUE THREAD

**Issue by gurleensethi** [android/android-ktx#190]
Most of the times applications contain `RecyclerView`'s that display simple linear data and every time one has to create a new adapter. There should be a generic class or an extension on `RecyclerView` with which we can create adapter without the need of creating a separate file. Something like this https://github.com/gurleensethi/LiteUtilities#recyclerutils.

**Comment by romainguy** [comment]
android-ktx does not cover the support library.

**Comment by gurleensethi** [comment]
Cool

**Comment by AyoGitNg** [comment]
Should we be expecting an android-support-ktx later. It would be great to have an official supported approach.
