### ISSUE TITLE
TypedArray.use()

### ISSUE THREAD

**Issue by daberni** [android/android-ktx#193]
```kotlin
inline fun TypedArray.use(block: (TypedArray) -> Unit) {
    try {
        block(this)
    } finally {
        recycle()
    }
}
```

for usage like this:

```kotlin
context.obtainStyledAttributes(attrs, R.styleable.TextView, 0, 0).use {
    val text = it.getString(R.styleable.TextView_text)
}
```

This would mimic the `Closeable` interface, see https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html

**Comment by romainguy** [comment]
This was on my to-do list, thanks for the reminder :)

**Comment by JakeWharton** [comment]
Do we need try/finally? A crash here _should_ take the entire process with it.

**Comment by EddieRingle** [comment]
@JakeWharton I believe it should. If the intention is to mimic the Kotlin standard library's `use`, it should have the same semantics:

> Executes the given block function on this resource and _then closes it down correctly whether an exception is thrown or not_.

**Comment by JakeWharton** [comment]
These are pooled objects. Not native file handles. I see no value in
introducing what is otherwise a code smell to maintain implementation
semantics to Kotlin's stdlib when we're merely trying to match usage
conventions. Simply omitting that clause from our documentation frees us
from it.

**Comment by daberni** [comment]
If you are catching the exception on a higher level, the TypedArray isn't recycled. But I am not into the inner workings of TypedArray. When `recycle()` isn't necessary at all, please deprecate it and remove it from the official docs. But as long this isn't the case this extension would be handy.

**Comment by JakeWharton** [comment]
You seem to be conflating best-effort pooling with actual leaks of resources. These are not equivalent.

**Comment by JakeWharton** [comment]
Also we are not debating the value of the extension but its implementation.

**Comment by daberni** [comment]
So it would be enough when replacing the `try-finally` block.

```
inline fun TypedArray.use(block: (TypedArray) -> Unit) {
    block(this)
    recycle()
}
```

**Comment by JakeWharton** [comment]
That is what I would be an advocate for, yes.

**Comment by JakeWharton** [comment]
Was merged.
