### ISSUE TITLE
Set elevation to View

### ISSUE THREAD

**Issue by AkshayChordiya** [android/android-ktx#200]
Adding an extension function to easily set elevation to `View`.

```
infix fun View.elevate(elevation: Float) {
    ViewCompat.setElevation(this, elevation)
}
```

I'm not sure if this should be part of android-ktx for framework or support library. I'm slightly baised towards support library but I see `ViewCompat` already used in [View.kt](https://github.com/android/android-ktx/blob/master/src/main/java/androidx/view/View.kt), hence the issue.

**Comment by daberni** [comment]
`ViewCompat` is part of the support library and therefore will not find it's way into this extension project.

`This project does not currently cover the Android Support Library or Architecture Components APIs.`

It would be more appropriate if the support library would convert it's `Compat` classes to kotlin extensions with proper fallbacks for Java. (I'm looking at you @JakeWharton 😉 )

**Comment by AkshayChordiya** [comment]
I agree with you @daberni and I am totally waiting for extensions for Android Support Library. But the only reason I created this issue is because I found `ViewCompat` already being used in [View.kt](https://github.com/android/android-ktx/blob/master/src/main/java/androidx/view/View.kt) which made me curious.
