### ISSUE TITLE
Wanting to help

### ISSUE THREAD

**Issue by dovahkiin98** [android/android-ktx#202]
I am sorry if this is not the place to ask such a thing. But I would love to help build this library.
I've seen some developers committing changes to the API and I was wondering if I can do the same, and if I can, what steps must I follow for my commit to be approved?

**Comment by Edward608** [comment]
1. Fork this repo
2. create issue on their issue tracker
3. Apon approval, add that in your forked repo
4. create a pull request in this repo

**Comment by daberni** [comment]
see https://github.com/android/android-ktx#how-to-contribute
