### ISSUE TITLE
Date/Time Formatter

### ISSUE THREAD

**Issue by the-cybersapien** [android/android-ktx#204]
For a lot of my user-facing projects, I often do something like this to parse Date from the server and parse it to the User's local format:
```kotlin
fun formatDate(dateString: String): String {
    val defaultDateFormat = SimpleDateFormat("dd-MM-yyyy", Locale.getDefault())
    val localeDateFormat = SimpleDateFormat.getInstance()
    val date = defaultDateFormat.parse(dateString)
    return localeDateFormat.format(date)
}
```

It'd be easier if we could simply use a single method, an example:
```kotlin
fun String.getLocalDateTime(initialFormat: String): String {}
``` 

Would like to work on this.

Similar implementations can be done for `String.getLocalTime(initialFormat: String)`, `String.getLocalDate(initialFormat: String)` as well.

**Comment by JakeWharton** [comment]
This is something that is sufficiently specific to a single application that we don't want to put it in a shared library. Moreover there's issues around allocation that are specific to whether the usage is thread-confined for concurrent.
