### ISSUE TITLE
Add `doOnEnd` for Animation and ValueAnimator

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#205]
Similar to this one:

https://android.github.io/android-ktx/core-ktx/androidx.animation/android.animation.-animator/do-on-end.html

But for Animation and ValueAnimator:
https://developer.android.com/reference/android/animation/ValueAnimator.html
https://developer.android.com/reference/android/view/animation/Animation.html

Here's a sample implementation, without extension functions:

``` kotlin 
    @JvmStatic
    fun runOnAnimationEnd(animation: Animation, runnable: Runnable) {
            animation.setAnimationListener(object : AnimationListener {

                override fun onAnimationStart(animation: Animation) {}

                override fun onAnimationRepeat(animation: Animation) {}

                override fun onAnimationEnd(animation: Animation) {
                    animation.setAnimationListener(null)
                    runnable.run()
                }
            })
    }

    @JvmStatic
    fun runOnAnimationEnd(animator: ObjectAnimator, runnable: Runnable): ObjectAnimator {
        animator.addListener(object : AnimatorListener {
            override fun onAnimationStart(animation: Animator) {}
            override fun onAnimationRepeat(animation: Animator) {}

            override fun onAnimationEnd(animation: Animator) {
                animator.removeListener(this)
                runnable.run()
            }

            override fun onAnimationCancel(animation: Animator) {}
        })
        return animator
    }
```

**Comment by LouisCAD** [comment]
Please, add `kotlin` after the 3 opening backticks (```) of your kotlin snippet

**Comment by AndroidDeveloperLB** [comment]
@LouisCAD What "3 opening backticks" ?

**Comment by LouisCAD** [comment]
@AndroidDeveloperLB See ["syntax highlighting" on this page](https://guides.github.com/features/mastering-markdown/).

**Comment by AndroidDeveloperLB** [comment]
Oh.... nice!

**Comment by LouisCAD** [comment]
@AndroidDeveloperLB You added an extra indentation level in turn, but yeah, nicer

**Comment by AndroidDeveloperLB** [comment]
That's not me. Clicking the button did it

**Comment by romainguy** [comment]
`android.view.animation` is the old animation system and we don't wish to promote it in android-ktx.

**Comment by romainguy** [comment]
`ObjectAnimator` is an `Animator`, therefore https://android.github.io/android-ktx/core-ktx/androidx.animation/android.animation.-animator/do-on-end.html would work.

**Comment by AndroidDeveloperLB** [comment]
Oh. Sorry .

**Comment by AndroidDeveloperLB** [comment]
But I still think Animation is missing here.
