### ISSUE TITLE
Request: add `setTextOrHide` - sets a text to a TextView, or hide it if empty

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#206]
Many times, when you have a text to set to a TextView, you set its visibility to be VISIBLE, yet when it's empty or null, you might want to make it INVISIBLE or GONE.

For this I use this function:

    @IntDef(View.VISIBLE.toLong(), View.INVISIBLE.toLong(), View.GONE.toLong())
    @Retention(RetentionPolicy.SOURCE)
    annotation class Visibility

    fun TextView.setTextOrHide(textToSet: CharSequence?, @ViewHelper.Visibility visibilityWhenEmpty: Int = View.GONE) {
        if (TextUtils.isEmpty(textToSet)) {
            visibility = visibilityWhenEmpty
            text = null
        } else {
            visibility = VISIBLE
            text = textToSet
        }
    }

**Comment by JakeWharton** [comment]
There's an unlimited "orHide" set of behaviors one could define for use in apps. Such a need is app-specific and more appropriate for definition in your codebase.

**Comment by AndroidDeveloperLB** [comment]
What do you mean? You mean it already exists?
Can you please post a link to what you mean, so that I could see how to use it?

**Comment by romainguy** [comment]
It doesn't exist in android-ktx but this behavior is very specific and is best implemented in your application or library.

**Comment by AndroidDeveloperLB** [comment]
It's not very specific. I used it a lot, in multiple apps.

**Comment by MGaetan89** [comment]
The condition to hide the view is specific.
What if someone wants to hide a `TextView` if it contains only spaces? Or a specific text?

**Comment by AndroidDeveloperLB** [comment]
@MGaetan89 Those are much less common. An empty text is more common than one with special empty spaces, or a specific text that should make the TextView disappear . 

Let's take an example: showing a person information. Fields include name, job, address,... 

If you have various fields to show, of a person data, and the user has entered some junk empty spaces, you would not save it as such, but instead you would save it as empty ones, because it shouldn't be shown anyway. 
Here, if the UI is supposed to show a field of "job" for the person, and the user hasn't entered anything there, or has put there some empty data (spaces alone, for example), you might want to avoid showing the field at all.

For specific text, I've never seen such a case needed. Do you have an example for it?
