### ISSUE TITLE
Setting a view background without affecting its padding

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#208]
Many times, when you wish to set a background to a view, you wish to keep its padding intact (because otherwise it will change).

For this, I made these functions:

```
fun View.setViewBackgroundWithoutResettingPadding(@DrawableRes backgroundResId: Int) {
    val paddingBottom = this.paddingBottom
    val paddingLeft = this.paddingLeft
    val paddingRight = this.paddingRight
    val paddingTop = this.paddingTop
    setBackgroundResource(backgroundResId)
    setPadding(paddingLeft, paddingTop, paddingRight, paddingBottom)
}

fun View.setViewBackgroundWithoutResettingPadding(background: Drawable) {
    val paddingBottom = this.paddingBottom
    val paddingLeft = this.paddingLeft
    val paddingRight = this.paddingRight
    val paddingTop = this.paddingTop
    ViewCompat.setBackground(this, background)
    setPadding(paddingLeft, paddingTop, paddingRight, paddingBottom)
}
```

There might be a problem with RTL though. Not sure if it should stay the way I wrote above, or we should use `ViewCompat.getPaddingStart` and `ViewCompat.getPaddingEnd`, including `setPaddingRelative`

**Comment by AndroidDeveloperLB** [comment]
OK, made a better one:

```
fun View.setViewBackgroundWithoutResettingPadding(@DrawableRes backgroundResId: Int) {
    val paddingBottom = this.paddingBottom
    val paddingStart = ViewCompat.getPaddingStart(this)
    val paddingEnd = ViewCompat.getPaddingEnd(this)
    val paddingTop = this.paddingTop
    setBackgroundResource(backgroundResId)
    ViewCompat.setPaddingRelative(this, paddingStart, paddingTop, paddingEnd, paddingBottom)
}

fun View.setViewBackgroundWithoutResettingPadding(background: Drawable) {
    val paddingBottom = this.paddingBottom
    val paddingStart = ViewCompat.getPaddingStart(this)
    val paddingEnd = ViewCompat.getPaddingEnd(this)
    val paddingTop = this.paddingTop
    ViewCompat.setBackground(this, background)
    ViewCompat.setPaddingRelative(this, paddingStart, paddingTop, paddingEnd, paddingBottom)
}
```

**Comment by JakeWharton** [comment]
This seems really specific. I'm not sure why it should be included in this library.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton You never had to set a background to a view, and noticed it ruins your padding of it?

**Comment by JakeWharton** [comment]
I'm aware of that behavior, yes.

**Comment by AndroidDeveloperLB** [comment]
And it didn't bother you?
To me it was actually surprising: why remove the padding I've set...

**Comment by JakeWharton** [comment]
Because the Drawable has padding.

**Comment by AndroidDeveloperLB** [comment]
So it should contain both. The drawable shouldn't affect such properties of the view. The View class already has padding.
To me it was confusing, and I'm not the only one. Here's a sample StackOverflow thread about it, a very long time ago: 
https://stackoverflow.com/questions/10095196/whered-padding-go-when-setting-background-drawable/20873849

I'm sure there might be others.

**Comment by AndroidDeveloperLB** [comment]
@romainguy Why close it?
There are functions for updating a single padding of a view without affecting the other padding, but there is no function for updating the background without affecting the padding.
