### ISSUE TITLE
Request: get tinted drawable out of a given one

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#210]
Sometimes, when you have a given drawable, and you wish to have a tinted version of it (colorized in a different color), this could be useful: 

```
fun Drawable.getTintedDrawable(context: Context, @ColorInt color: Int): Drawable {
    val wrapDrawable = DrawableCompat.wrap(mutate())
    DrawableCompat.setTint(wrapDrawable, color)
    DrawableCompat.setTintMode(wrapDrawable, Mode.SRC_IN)
    return wrapDrawable
}
```

**Comment by romainguy** [comment]
This library is not meant to provide extensions for the support library.

**Comment by AndroidDeveloperLB** [comment]
OK, then, how about getting a mirrored Drawable, that should be useful for RTL support ? It doesn't require the support library this way:

```
fun Drawable.getMirroredDrawable(): Drawable {
    return object : LayerDrawable(arrayOf(this)) {
        val matrix = Matrix()
        override fun draw(canvas: Canvas) {
            matrix.reset()
            matrix.preScale(-1.0f, 1.0f, canvas.width / 2.0f, canvas.height / 2.0f)
            canvas.matrix = matrix
            setBounds(0, 0, canvas.width, canvas.height)
            super.draw(canvas)
        }
    }
}
```

I've used it, for example, when mirroring wasn't supported on drawables, as it's available only from API 19 ( `autoMirrored` ) .

**Comment by romainguy** [comment]
Why does this build a LayerDrawable? Also you cannot rely on Canvas' width and height as with software rendering it might be the dimensions of the window (or of the target render bitmap/surface). There's no guarantee that they are the dimensions of the source drawable. You should also not be changing the bounds during draw.

**Comment by AndroidDeveloperLB** [comment]
@romainguy Because I didn't find a more suitable Drawable .
I did it for rotating a drawable too: 

```
fun Drawable.getRotateDrawable(angle: Int): Drawable {
    if (angle % 360 == 0)
        return this
    val d = this
    return object : LayerDrawable(arrayOf(d)) {
        override fun draw(canvas: Canvas) {
            canvas.save()
            canvas.rotate(angle.toFloat(), (d.bounds.width() / 2).toFloat(), (d.bounds.height() / 2).toFloat())
            super.draw(canvas)
            canvas.restore()
        }
    }
}
```

How should I have made the code? I had to handle this issue because of this:
https://stackoverflow.com/q/48283208/878126

I'm quite a noob with creating customized drawables, sadly. I tried what I've found, but it didn't work, so I asked for help on StackOverflow, and got this answer, and only made it a bit nicer with Kotlin.

**Comment by AndroidDeveloperLB** [comment]
@romainguy If you have a nicer solution (for both rotating and mirroring of a Drawable), please feel free to write about it on the StackOverflow post I made. I can grant you a bounty if you wish :)

**Comment by AndroidDeveloperLB** [comment]
ok created a new request for the mirrored drawable: 
https://github.com/android/android-ktx/issues/220
