### ISSUE TITLE
Request: set specific padding in one side (top/bottom/start/end)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#211]
If you wish to set padding to a view, but only change one side of it, instead of all of them, you can't do it using the normal API, because it has only getter functions.

This is why I made this:

```
    //TODO use IntDef instead
    enum class ViewPadding {
        START_OR_LEFT, BOTTOM, END_OR_RIGHT, TOP
    }

fun View.setPaddingOrRelativePadding(paddingType: ViewHelper.ViewPadding, paddingValueToSetInPixels: Int) {
    when (paddingType) {
        ViewHelper.ViewPadding.BOTTOM -> ViewCompat.setPaddingRelative(this, ViewCompat.getPaddingStart(this), this.paddingTop, ViewCompat.getPaddingEnd(this), paddingValueToSetInPixels)
        ViewHelper.ViewPadding.END_OR_RIGHT -> ViewCompat.setPaddingRelative(this, ViewCompat.getPaddingStart(this), this.paddingTop, paddingValueToSetInPixels, this.paddingBottom)
        ViewHelper.ViewPadding.START_OR_LEFT -> ViewCompat.setPaddingRelative(this, paddingValueToSetInPixels, this.paddingTop, ViewCompat.getPaddingEnd(this), this.paddingBottom)
        ViewHelper.ViewPadding.TOP -> ViewCompat.setPaddingRelative(this, ViewCompat.getPaddingStart(this), paddingValueToSetInPixels, ViewCompat.getPaddingEnd(this), this.paddingBottom)
    }
}
```

**Comment by JakeWharton** [comment]
This already exists as `updatePadding`.

**Comment by AndroidDeveloperLB** [comment]
Nice. And you probably mean this:
https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view/update-padding-relative.html

But why 2 functions instead of one?
https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view/update-padding.html

I think the updatePaddingRelative should be enough, no?

**Comment by JakeWharton** [comment]
No. It's API 17+.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton So my function handles both, without requirement of API version.
Sadly, as you wrote somewhere else, it requires the support library.

If we want to use the functions of the current repo, we will have to do a version check.
Can you please make it a single function using what's available there?

**Comment by JakeWharton** [comment]
The goal was to adapt the platform APIs for which there are also two
functions.

**Comment by AndroidDeveloperLB** [comment]
But this means that if the minSdk isn't 17+ , we will need to perform a version check.
Don't you think my function is better in this case?
At the very least, you could merge the 2 functions to one, that has the version check:

```
fun View.setPaddingOrRelativePadding2(paddingType: ViewHelper.ViewPadding, paddingValueToSetInPixels: Int) {
    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN_MR1) {
        when (paddingType) {
            ViewHelper.ViewPadding.BOTTOM -> updatePaddingRelative(bottom = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.END_OR_RIGHT -> updatePaddingRelative(end = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.START_OR_LEFT -> updatePaddingRelative(start = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.TOP -> updatePaddingRelative(top = paddingValueToSetInPixels)
        }
    } else
        when (paddingType) {
            ViewHelper.ViewPadding.BOTTOM -> updatePadding(bottom = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.END_OR_RIGHT -> updatePadding(right = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.START_OR_LEFT -> updatePadding(left = paddingValueToSetInPixels)
            ViewHelper.ViewPadding.TOP -> updatePadding(top = paddingValueToSetInPixels)
        }
}
```

Of course, this should be shorter, to use the exact parameter instead of having to use the enum as I used, but you get what I mean...
