### ISSUE TITLE
Attach sources to the maven repository

### ISSUE THREAD

**Issue by LouisCAD** [android/android-ktx#212]
When I ctrl/cmd+click on a symbol from the library, it shows "compiled code" instead of showing the source of this open source project. The sources should be attached in the repository so Android Studio can properly recognize them.

**Comment by JakeWharton** [comment]
Dupe #171.

**Comment by LouisCAD** [comment]
@JakeWharton Missing sources and 404 doc link are the same issue?

**Comment by JakeWharton** [comment]
The sources are already in the Maven repository. What's wrong with them?

**Comment by LouisCAD** [comment]
The issue is more complex than I thought.
When I ctrl/cmd+click on a ktx symbol from my code, I get to see the code, but when I click on a ktx class file from "External libraries" in the project View, the IDE (Android Studio 3.0.1) doesn't show the sources.

This is not a behavior I get with kotlinx.coroutines.android (except, mysteriously, some symbols), but I believe this is Android Studio related now. I'm closing this issue and will report on b.android.com

**Comment by JakeWharton** [comment]
Hmm that's unfortunate. But glad it at least works from the more common location of stepping into it.

**Comment by LouisCAD** [comment]
Here's the link of the Android Studio issue: https://issuetracker.google.com/issues/72937420
