### ISSUE TITLE
Request: add efficient replacement of items within an ArrayList

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#213]
I've made in the past a way to replace items from index to index, in an efficient manner, while creating minimal number of objects:

    fun <T> ArrayList<T>.replaceItems(fromIndex: Int, toIndexExcluding: Int, deltaItems: ArrayList<T>) {
        if (fromIndex > toIndexExcluding)
            throw IllegalArgumentException("bad indices: $fromIndex should be <=$toIndexExcluding")
        if (fromIndex < 0)
            throw IllegalArgumentException("bad index to start from: $fromIndex should be >=0")
        if (toIndexExcluding > size)
            throw IllegalArgumentException("bad index : $toIndexExcluding should <= list size $size")
        var indexToTakeItemFrom = 0
        val minEnsuredCapacity = size - (toIndexExcluding - fromIndex) + deltaItems.size
        ensureCapacity(minEnsuredCapacity)
        //replacing items:
        var i = fromIndex
        while (i < toIndexExcluding && i < size) {
            if (indexToTakeItemFrom >= deltaItems.size) {
                subList(i, toIndexExcluding).clear()
                return
            }
            set(i, deltaItems[indexToTakeItemFrom++])
            ++i
        }
        //add remaining items
        addAll(fromIndex + indexToTakeItemFrom, deltaItems.subList(indexToTakeItemFrom, deltaItems.size))
    }

Example inputs&outputs: 

```
//deltaList is a integer list with just 2 items: {99,100}

// list is {0,1,2,3,4,5}
replaceItems(list, 1, 1, deltaList) //nothing to replace, so just add {99,100} to index 1
//list is now {0,99,100,1,2,3,4,5}

// list is {0,1,2,3,4,5}
replaceItems(list, 1, 2, deltaList) //replace {1} with {99,100}
//list is now {0,99,100,2,3,4,5}

// list is {0,1,2,3,4,5}
replaceItems(list, 1, 3, deltaList) //replace {1,2} with {99,100}
//list is now {0,99,100,3,4,5}

// list is {0,1,2,3,4,5}
replaceItems(list, 1, 4, deltaList) //replace {1,2,3} with {99,100}
//list is now {0,99,100,4,5}
```

**Comment by JakeWharton** [comment]
Mutators for MutableList should be proposed to the Kotlin stdlib at https://youtrack.jetbrains.com/issues/KT

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton I don't understand what you mean.
You mean it's available?
What's wrong with the code I wrote?

**Comment by JakeWharton** [comment]
It's not for the Android APIs.

**Comment by AndroidDeveloperLB** [comment]
It's even more generic, you mean, so you suggest I should write it there?

**Comment by romainguy** [comment]
android-ktx is meant to provide extensions to Android APIs. ArrayList is a base Java API and extensions for it should be in Kotlin's standard runtime library instead.

**Comment by AndroidDeveloperLB** [comment]
OK I've created a new issue here:
https://youtrack.jetbrains.com/issue/KT-22726
