### ISSUE TITLE
Allow to get a mirrored Drawable out of a given one

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#220]
This should be useful for RTL support ? It doesn't require the support library this way. I've used it, for example, when mirroring wasn't supported on drawables, as it's available only from API 19 ( `autoMirrored` ) .

I tried to create the next code, but was told it's not that good ([here](https://github.com/android/android-ktx/issues/210#issuecomment-363435857)) :

```kotlin
fun Drawable.getMirroredDrawable(): Drawable {
    return object : LayerDrawable(arrayOf(this)) {
        val matrix = Matrix()
        var isInitialized = false
        override fun draw(canvas: Canvas) {
            matrix.reset()
            matrix.preScale(-1.0f, 1.0f, canvas.width / 2.0f, canvas.height / 2.0f);
            canvas.matrix = matrix
            if (!isInitialized) {
                val drawingRect = Rect()
                drawingRect.left = (canvas.width - intrinsicWidth) / 2
                drawingRect.top = (canvas.height - intrinsicHeight) / 2
                drawingRect.right = drawingRect.left + intrinsicWidth
                drawingRect.bottom = drawingRect.top + intrinsicHeight
                bounds = drawingRect
                isInitialized = true
            }
            super.draw(canvas)
        }
    }
}
```

**Comment by JakeWharton** [comment]
This seems like something that should be on DrawableCompat and not specific to this library.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton That's true. But it's also true for all functions of this library.
All can be in the support library instead of here. 
Anyway, I've created a new request here:
https://issuetracker.google.com/issues/72937426

**Comment by JakeWharton** [comment]
No. It is absolutely not true of all functions in this library.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton I don't think there is any code on Kotlin here that can't be implemented in Java on the support library.

**Comment by JakeWharton** [comment]
Then you would be incorrect. Thanks.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton Why? Which function do you know in Kotlin that can't be implemented in Java?
As far as I know, Kotlin code is converted to bytecode and can be called from Java, just like a normal Java function.
The only different is the syntax a potentially more time needed to write the code.

**Comment by romainguy** [comment]
This feature is better suited for the support library. We try to avoid adding new features in android-ktx, just make existing APIs easier to use. It's a fine (and somewhat blurry) line but this definitely falls outside of the scope of this library.

**Comment by AndroidDeveloperLB** [comment]
@romainguy OK, but I would still like to know your professional opinion on what (and how) could be improved on the code (here: https://stackoverflow.com/questions/48283208/how-to-get-a-drawable-thats-a-mirrored-version-of-a-different-drawable ) .
