### ISSUE TITLE
Bitmap toJpeg(), toPng(), toWebp() extensions

### ISSUE THREAD

**Issue by rom4ek** [android/android-ktx#236]
I think it would make sens to have something like
```Kotlin
fun Bitmap.toJpeg()
```
which would either return `ByteArray` or `Bitmap`. What do you guys think? Or it should be done on `OutputStream` or even `File` level?

**Comment by JakeWharton** [comment]
Can you describe your use case more? What are you doing that requires you to do this?

**Comment by rom4ek** [comment]
For instance:
1. I have an app which deals with custom camera stuff (transforming output, drawing something on the output) and I have this compressing there. 
2. I have another app, which has functionality of cropping user's avatar, and I also have to compress bitmap as jpeg there.

So I think it would be convenient to have this extension, so we could do something like
```Kotlin
bitmap.toJpeg().run {
    outputStream.write(this, 0, size)
}
```

Or it would be even more easier to use, if it would be a `File` class extension
```Kotlin
fun File.saveAsJpeg(bitmap: Bitmap)
```

**Comment by romainguy** [comment]
It doesn't offer much more than Bitmap.compress and your example would be a lot less efficient than compressing directly to a stream
