### ISSUE TITLE
JSONObject & JSONArray extensions

### ISSUE THREAD

**Issue by ethanblake4** [android/android-ktx#241]
Although these aren't in the `android.*` package, `JSONObject` / `JSONArray` are included as part of Android, and they are really quite a pain to work with in Kotlin (for example, `JSONArray` does not even implement `Iterable`, so none of Kotlin's collections framework works with it. Additionally, `JSONObject`'s behavior of throwing an exception instead of `null` when a value is not provided in any of the `get*` methods can be very unhelpful at times.)

I propose for `JSONObject` that the following base function is added:
```kotlin
private inline fun <T> JSONObject.getOrNull(
        key: String?,
        getter: JSONObject.() -> T
) = if(key == null) null else {
        if (has(key)) getter(this) else null
    }
```

Enabling the creation of the following functions:

```kotlin
fun JSONObject.getIntOrNull (key: String?): Int? = getOrNull(key, { getInt(key) })
fun JSONObject.getStringOrNull (key: String?): String? = getOrNull(key, { getString(key) })
fun JSONObject.getBoolOrNull (key: String?): Boolean? = getOrNull(key, { getBoolean(key) })
... etc ...
```

For `JSONArray`, I propose that at the very least, a `toList()` function should be added:
```kotlin
inline fun <reified T> JSONArray.toList() = List(length(), { i -> get(i) as? T })
```
Taking it a step further, I would like to re-implement the majority of kotlin's `Collections` framework over `JSONArray`. Some examples:

```kotlin
// Mapping
inline fun <reified T, R> JSONArray.map(transform: (T?) -> R): MutableList<R?> =
        mapTo(mutableListOf(), transform)

inline fun <reified T, R> JSONArray.mapTo(to: MutableList<R?>, transform: (T?) -> R): MutableList<R?> =
        (0..length()).mapTo(to, { i -> transform(get(i) as? T) })

inline fun <reified T, R> JSONArray.mapNotNull(transform: (T) -> R): MutableList<R> =
        mapNotNullTo(mutableListOf(), transform)

inline fun <reified T, R> JSONArray.mapNotNullTo(to: MutableList<R>, transform: (T) -> R): MutableList<R> =
        to.apply {
            (0..length()).forEach { i -> (get(i) as? T)?.let { add(transform(it)) } }

inline fun <reified T, R> JSONArray.mapIndexed(transform: (index: Int, T?) -> R): MutableList<R?> =
        mapIndexedTo(mutableListOf(), transform)

inline fun <reified T, R> JSONArray.mapIndexedTo(
        to: MutableList<R?>,
        transform: (index: Int, T?) -> R?
): MutableList<R?> =
        (0..length()).mapTo(to, { i ->  transform(i, get(i) as? T) }  )


// Iteration
inline fun <reified T> JSONArray.forEach(action: (T?) -> Unit) {
    (0..length()).forEach { action(get(it) as? T) }
}

inline fun <reified T> JSONArray.forEachIndexed(action: (index: Int, T?) -> Unit) {
    (0..length()).forEach { action(it, get(it) as? T) }
}

inline fun <reified T> JSONArray.forEachNotNull(action: (T) -> Unit) {
    (0..length()).forEach { action(get(it) as T) }
}

// Summary
inline fun <reified T: Comparable<T>> JSONArray.max() =
        toList<T>().filterNotNull().max()

inline fun <reified T: Comparable<T>> JSONArray.min() =
        toList<T>().filterNotNull().min()

... etc ...
```

Finally, I would like to implement operators on `JSONArray`:
```kotlin

operator fun JSONArray.plus(other: Any?) : JSONArray {
    return JSONArray(toList<Any?>()).apply { plusAssign(other) }
}

operator fun JSONArray.plusAssign(other: Any?) {
    put(other)
}

operator fun JSONArray.set(index: Int, other: Any?) {
    put(index, other)
}
```

As you can see, I already have most of this written, so let me know which parts seem acceptable, if any, and I'll write up some tests and create a pull request.

**Comment by JakeWharton** [comment]
I would like to advocate that these are best suited for a third-party library focused specifically on this API for a few reasons:
 1. We're trying to focus on `android.*` APIs as you said. The extensions that I wrote for `java.time.*` I'm actively trying to kill and upstream to move into a separate library.
 2. `org.json.*` is usable outside Android so they would be usable to anyone consuming this library.
 3. No one should use these APIs. We should really sunset them the same way we did the Apache APIs. It's so weird that they're in the platform. (Insert obligatory "in my opinions" here)

**Comment by ethanblake4** [comment]
I agree with your points. 

In this case, the unfortunate truth is that the `org.json.*` APIs are the only JSON APIs (besides the incredibly abstract `JsonWriter`) included with Android and therefore _are_ used, especially by beginners (the top result when doing a Google search for "android json" is [this page](https://developer.android.com/reference/org/json/JSONObject.html), and only one of the top ten results advocates the use of third-party libraries).

Despite that, I see that these extensions wouldn't be a good fit for this package, so I'm closing the issue.
