### ISSUE TITLE
SharedPreferences extensions

### ISSUE THREAD

**Issue by sourabhv** [android/android-ktx#243]
I know there is an `edit` extension on SharedPreferences but using it when updating single value is still a lot of code

```
sharedPreferences.edit {
    putBoolean("key", false)
}
```

Well, maybe not a lot, but still...

___

Here's what I propose, an overloaded `put` method for every type that `SharedPreferences` supports and a `set` operator function as well

```
fun SharedPreferences.Editor.put(key: String, value: String) = putString(key, value)
operator fun SharedPreferences.set(key: String, value: String) = edit {
    put(key, value)
}

fun SharedPreferences.Editor.put(key: String, value: Set<String>) = putStringSet(key, value)
operator fun SharedPreferences.set(key: String, value: Set<String>) = edit {
    put(key, value)
}

fun SharedPreferences.Editor.put(key: String, value: Int) = putInt(key, value)
operator fun SharedPreferences.set(key: String, value: Int) = edit {
    put(key, value)
}

fun SharedPreferences.Editor.put(key: String, value: Long) = putLong(key, value)
operator fun SharedPreferences.set(key: String, value: Long) = edit {
    put(key, value)
}

fun SharedPreferences.Editor.put(key: String, value: Float) = putFloat(key, value)
operator fun SharedPreferences.set(key: String, value: Float) = edit {
    put(key, value)
}

fun SharedPreferences.Editor.put(key: String, value: Boolean) = putBoolean(key, value)
operator fun SharedPreferences.set(key: String, value: Boolean) = edit {
    put(key, value)
}
```

So the above code can be written as 

```
sharedPreferences.put("key", false)
sharedPreferences["key"] = false
```

**Comment by MGaetan89** [comment]
#217 will deprecate `edit()` to be more explicit about the actual save action (`apply()` or `commit()`).
So it will be harder to integrate this change, even if it looks quite nice.

**Comment by sourabhv** [comment]
Does anyone even use `commit`? And #217 is still under debate.

Also, `get` can be added to the above snippet as well.

**Comment by MGaetan89** [comment]
Yes, the PR is not merged. I juste wanted to make sure that you're aware of the other discussion ;)

**Comment by chrisbln** [comment]
Also possible:
```
operator fun SharedPreferences.set(key: String, value: Any?) {
    when (value) {
        is String -> edit({ it.putString(key, value) })
        is Boolean -> edit({ it.putBoolean(key, value) })
        is Int -> edit({ it.putInt(key, value) })
        // more cases...
        else -> throw UnsupportedOperationException()
    }
}
```

**Comment by sourabhv** [comment]
@chrisbln Passing an unsupported value would throw an exception at runtime instead of compile time, which is why I suggested overloaded set methods.

**Comment by davethomas11** [comment]
Very similar to this blog post https://medium.com/@krupalshah55/manipulating-shared-prefs-with-kotlin-just-two-lines-of-code-29af62440285

I'd probably do something like this to make array access available on shared preferences, as this is very convenient and concise. I am curious though, about the reason for keeping the edit call around.

Looking at it, my thinking is this, shared preferences stores the changes in an XML file on disk. Writing this requires IO. To minimize IO, doing multiple changes at once is more efficient?

Ie. 
preferences["One"] = 1
preferences["Two"] = 2

Would this potentially trigger two asynchronous actions to write to disk when apply is called?

Verse:

preferences.edit {
  it["One"] = 1
  it["Two"] = 2
}

Which would only make one apply call?  I'm asking to see whether I am correct in these assumptions or not.

What is the importance of edit?

---

Ok... answering my own curiosity here. I looked at https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/SharedPreferencesImpl.java 

It is apparent that n+ consecutive calls to apply is more expensive. Edit is important for this reason. You don't want to unintentionally queue up more disk writes than you need to. 

Exposing the API this way to the general public may allow developers to make some unwary additions to their code.

If you like this style, I suggest being aware of the impact and adding it yourself to your code base. 
As I would and use it sparingly while being aware of the consequences.

**Comment by davethomas11** [comment]
For the above reason, my vote is in disapproval of this change.

**Comment by sourabhv** [comment]
@davethomas11 Yes I am aware it will cause multiple async calls and my initial proposal stared that I wrote these for only when updating one value. But I agree, it might cause people to use if for multiple updates.

If we are going to use `edit`/`apply`/`commit` extension function then maybe we can do something like this

```
prefs.apply {
    "foo" to "bar"
    "answer" to 42
}
```

PS: Can't a lint check detect multiple `set`/`put` calls one after another? I've never written lint rules

**Comment by chrisbln** [comment]
@sourabhv Your are right, this would be more runtime error prone.

**Comment by JakeWharton** [comment]
It's not clear that there's any value here. We just seem to be code golfing on an API that isn't used much and it's really that verbose in the first place.
