### ISSUE TITLE
Context.sendLocalBroadcast for LocalBroadcastManager

### ISSUE THREAD

**Issue by clhols** [android/android-ktx#247]
Context has sendBroadcast and sendOrderedBroadcast methods. So what about adding a sendLocalBroadcast extension function:

```kotlin
fun Context.sendLocalBroadcast(intent: Intent) {
    LocalBroadcastManager.getInstance(this).sendBroadcast(intent)
}
```

Or should it be in the support lib since that is where LocalBroadcastManager is?

**Comment by JakeWharton** [comment]
These extensions are only for the platform, not support libraries.
