### ISSUE TITLE
Any extensions for MediaPlayer or MediaService in future?

### ISSUE THREAD

**Issue by wbinarytree** [android/android-ktx#259]
I worked for a MediaPlayback app but see some of boilerplate code . For example, the convert between `MediaItem`, `MediaDescription` and `QueueItem`
And there are tons of different callbacks.
Would this library cover classes in  `android.media` or even nicer with support library. Because new apis in media are introduced in api-21.

**Comment by JakeWharton** [comment]
Yes, those APIs are covered. If you have specific proposals please create an individual issue or PR for them.
