### ISSUE TITLE
Extension for setTint using DrawableCompat

### ISSUE THREAD

**Issue by jitinsharma** [android/android-ktx#261]
DrawableCompat has a `setTint` method but requires drawable to be wrapped using `wrap` method. We can combine both like this

```kotlin
fun Drawable.withTint(colorInt: Int): Drawable {
    return with(this) {
        DrawableCompat.wrap(this).apply {
            DrawableCompat.setTint(this, colorInt)
        }
    }
}
```

**Comment by JakeWharton** [comment]
Extensions in this project are only for platform APIs. If, hypothetically, "ktx" artifacts for support libraries come in the future this will be a good candidate for those.
