### ISSUE TITLE
Simplifying Fragment newInstance() implementation

### ISSUE THREAD

**Issue by overengineered** [android/android-ktx#270]
I often create companion methods for Fragments that create new instance of the fragment and a helper to initialise arguments for that new instance is really helpful, e.g.:

    class MyFragment : Fragment() {
        companion object {
            const val LABEL = "label"
            const val INDEX = "index"
    
            fun newInstance(label: String, value: Int): PostFragment {
                return MyFragment().withArguments {
                    putString(LABEL, label)
                    putInt(INDEX, index)
                }
            }
        }
     }

Possible implementation

    inline fun <T: Fragment> T.withArguments(block: Bundle.() -> Unit): T
            = this.apply { arguments = Bundle().apply(block) }

**Comment by JakeWharton** [comment]
We aren't adding any extensions for platform fragments (https://github.com/android/android-ktx/pull/161#issuecomment-363270555) and this library isn't targeted for support library fragments.
