### ISSUE TITLE
Bundle state handling via delegation

### ISSUE THREAD

**Issue by gabrielhuff** [android/android-ktx#272]
Take advantage of delegation in order to simplify bundle state management. There could be an API whose usage would look like this:

```kotlin
class MyActivity :  Stateful by stateful(), Activity() {
  
  // These will be automatically restored / saved on the instance state bundle
  private var count by state(0)
  private var name by state("A")
  
  override fun onCreate(state: Bundle?) {
    super.onCreate(state)
    restore(state)
  }
  
  override fun onSaveInstanceState(state: Bundle) {
    super.onSaveInstanceState(state)
    save(state)
  }
}
```
The `Stateful` interface would be something like:

```kotlin
interface Stateful {
  
  /**
   * The following methods register properties to be restored / saved during calls
   * to restore() / state()
   */
  fun state(initialValue: Int): ReadWriteProperty<Stateful, Int>
  fun state(initialValue: String): ReadWriteProperty<Stateful, String>
  // ...
  
  /**
   * Set all registered properties to values from the input bundle
   */
  fun restore(state: Bundle?)
  
  /**
   * Get all registered property values and put them on the input bundle
   */
  fun save(state: Bundle)
}
```

The `stateful()` method returns an implementation of `Stateful`. It'd be used by activities in order to implement `Stateful` by delegation.

Some of the advantages include:

- No need to worry about state bundle keys (or bundles in general) as this is delegated to the `Stateful` implementation
- Pretty handy in cases where there's a lot of state to be managed
- It can be used not only by subclasses of `Activity`, but also by `View`, `Fragment` or whatever other class that uses state bundles

**Comment by JakeWharton** [comment]
This is quite a bit of machinery that could be its own library and not in a one such as this which is focused on adapting platform APIs to feel idiomatic in Kotlin. This mechanism also requires lint rules to ensure that you are calling the `restore` and `save` methods appropriately.
