### ISSUE TITLE
Activity extension for showing dialogs

### ISSUE THREAD

**Issue by abyrnes** [android/android-ktx#276]
Activity extension for showing alert dialogs without having to explicitly invoke the constructor or call `create()/show()`.

```kotlin
inline fun Activity.alert(builder: AlertDialog.Builder.() -> Unit) {
    AlertDialog.Builder(this).apply {
        builder()
    }.show()
}
```

Also enforces the use of an activity as the `AlertDialog.Builder`'s context

**Comment by JakeWharton** [comment]
This isn't a recommended way to show a dialog so I wouldn't want to encourage it here either. You need to either use managed dialogs or support fragments so that they handle configuration changes.
