### ISSUE TITLE
Context extension for commonly used system service

### ISSUE THREAD

**Issue by Edward608** [android/android-ktx#280]
For example `val Context.inputMethodManager get() = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager`.

For Api >= 23, `fun <reified T> Context.getSystemService(): T = getSystemService(T::class.java)` could be used instead.

**Comment by oldergod** [comment]
https://github.com/android/android-ktx/blob/233e2cbf1e057b887b20e79d651dff1c4281ad98/src/main/java/androidx/content/Context.kt#L35-L37

**Comment by Edward608** [comment]
Didn't notice that, thanks.
