### ISSUE TITLE
Context.systemService on API > 23

### ISSUE THREAD

**Issue by dovahkiin98** [android/android-ktx#282]
I was wondering if it is possible to make this method
```kotlin
systemService<InputMethodManager>()
```
work on API less than 23.

would something like this work?

```kotlin
inline fun <reified T>Context.systemService() {
    when(T::class.java) {
        InputMethodManager::class.java -> getSystemService(Context.INPUT_METHOD_SERVICE)
        ConnectivityManager::class.java -> getSystemService(Context.CONNECTIVITY_SERVICE)
        AudioManager::class.java -> getSystemService(Context.AUDIO_SERVICE)
    }
}
```

I know there are about 60 services, and this will be an overhead, I was just wondering if there is a better way to do it.

**Comment by daberni** [comment]
would call it `getSystemService<>()` to match with the framework implementation. But I would prefer this to implement extra methods for each service like `getInputMethodService()` etc

**Comment by dovahkiin98** [comment]
Still would be a great method count, 60 services means 60 methods

**Comment by daberni** [comment]
Maybe my comment was not clear: I support your suggestion 😉

**Comment by neworld** [comment]
60 methods don't look much. Proguard should remove all unused. And, you get nicer API:
```kotlin
val currentInputBinding = context.inputMethodService.currentInputBinding
```
instead of:
```kotlin
val currentInputBinding = context.getSystemService<InputMethodService>().currentInputBinding
```

**Comment by daberni** [comment]
they should be inlined anyway, so the method count is 0 !!

**Comment by Jeff11** [comment]
What's even worse, I didn't get any lint warning nor compile warning/error for using systemService<..>(), although my minSdk is below 23.

**Comment by dovahkiin98** [comment]
@neworld 
so you're suggesting something like this
```kotlin
val inputService = getSystemService(Context.INPUT_METHOD_SERVICE)
val connectivityService= getSystemService(Context.CONNECTIVITY_SERVICE)
val audioService= getSystemService(Context.AUDIO_SERVICE)
```

**Comment by neworld** [comment]
@dovahkiin98, not exactly. I am suggesting do not use backing field:
```kotlin
inline val context.inputMethodService: InputMethodService
    get() = getSystemService(Context.INPUT_METHOD_SERVICE)
```

**Comment by JakeWharton** [comment]
Those would have to be nullable. It's not clear what services are guaranteed to be available or not, and the non-nullness of the return value is sometimes the only way to determine the presence or absence of a feature. Additionally, anyone can override `getSystemService` on a `Context` and return `null` for any service which is also slightly awkward. Nullable properties for these reduce their utility, sadly, and so for now we left them out for want of a better solution.

You'll notice the reified function we provide intentionally propagates a platform type to work around this problem which is something we can't do with these properties.

**Comment by neworld** [comment]
Make sense. Also, with reified function, you didn't lose lint check. All methods throw a warning:

![image](https://user-images.githubusercontent.com/38703/36693605-7a1a4690-1b44-11e8-8f59-65498e120df6.png)

**Comment by JakeWharton** [comment]
Trying to land a backwards-compatible version of this into support-compat at which point we can change the implementation to use that and drop the requires API. No action to take until that lands, though.
