### ISSUE TITLE
Snackbar extensions on View

### ISSUE THREAD

**Issue by simonschiller** [android/android-ktx#283]
Similar to #143 I would suggest adding convenience functions for creating Snackbars. However snackbars are a little bit more complex, as they can have actions. Maybe the function could look something like this:

```
fun View.snackbar(text: CharSequence,
                  duration: Int = Snackbar.LENGTH_SHORT,
                  actionText: CharSequence? = null,
                  action: ((View) -> Unit)? = null
): Snackbar { ... }
```

Another way could be to create a small DSL which could be used like this:

```
View.snackbar("Snackbar message", Snackbar.LENGTH_LONG) {
    action("Action message") { /* Some action code */ }
}
```

**Comment by dovahkiin98** [comment]
This repo is not currently for support APIs
