### ISSUE TITLE
Add recursive Sequence<View> to ViewGroup for recursive child looping

### ISSUE THREAD

**Issue by Edward608** [android/android-ktx#295]
I know there is a pull request which get merged by providing `Sequence<View>` for ViewGroup, but it only returns the direct child of the viewGroup, I wonder if anyone found it useful to have a version that iterate recursively if child is a `ViewGroup`.

**Comment by JakeWharton** [comment]
Dupe of #209. Let's keep discussion there. Actual use cases welcome.
