### ISSUE TITLE
Extensions for Menu/SubMenu/MenuItem

### ISSUE THREAD

**Issue by nic0lette** [android/android-ktx#300]
It would be helpful to have even basic support such as:

    MenuItem.visible
    MenuItem.enabled

etc...

Bigger thing could be:

    Menu += MenuItem
    Menu -= MenuItem

**Comment by simonschiller** [comment]
The former already is part of the standard API, you can use
```
MenuItem.isVisible
MenuItem.isEnabled
```

**Comment by nic0lette** [comment]
Yes, but one cannot do:

    MenuItem.visible = true

Only

    MenuItem.setVisible(true)

At the moment. That's the much more interesting part (to me) :)

**Comment by simonschiller** [comment]
You can call
```
MenuItem.isVisible = true
```
See the [Kotlin Java Interop Guide](https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters) for details.

**Comment by jaredsburrows** [comment]
Is it safe to close this issue since this feature already exists? @JakeWharton
