### ISSUE TITLE
Extensions for TextUtils functions

### ISSUE THREAD

**Issue by jitinsharma** [android/android-ktx#310]
Some functions from TextUtils class which would be useful as extensions

```kotlin
fun CharSequence.isDigitsOnly(): Boolean = TextUtils.isDigitsOnly(this)
fun CharSequence.isEmpty(): Boolean = TextUtils.isEmpty(this)
fun CharSequence.trimmedLength(): Int = TextUtils.getTrimmedLength(this)
fun String.htmlEncode(): String = TextUtils.htmlEncode(this)
fun Locale.getLayoutDirection(): Int = TextUtils.getLayoutDirectionFromLocale(this)
```

**Comment by JakeWharton** [comment]
`isEmpty` already exists in the Kotlin stdlib. Didn't someone already PR layout direction? PRs welcome for the rest.

**Comment by romainguy** [comment]
There's a PR pending for layout direction already. I just requested a couple of minor changes but I was going to approve it. PR #316

**Comment by jitinsharma** [comment]
I have referenced the PR for layoutdirection.
@JakeWharton For others, is it advisable to create files named Strings.kt, CharSequence.kt as same names are also present in kotlin stdlib.
Or would it be better to create something like TextUtils.kt

**Comment by JakeWharton** [comment]
These were merged.
