### ISSUE TITLE
CharSequence / String fromHtml()

### ISSUE THREAD

**Issue by avaytsekhovskiy** [android/android-ktx#317]
What do you think about such extension?

```kotlin
fun CharSequence.fromHtml(flags: Int? = null): Spanned {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
        Html.fromHtml(this.toString(), flags ?: Html.FROM_HTML_MODE_LEGACY)
    } else {
        Html.fromHtml(this.toString())
    }
}
```

**Comment by simonschiller** [comment]
Why don't use `flags: Int = Html.FROM_HTML_MODE_LEGACY`?

**Comment by avaytsekhovskiy** [comment]
@simonschiller `Html.FROM_HTML_MODE_LEGACY` flag available only for API N+. 

if we put it as default value for argument - it makes whole extension available for API N+ @RequiresApi(Build.VERSION_CODES.N)

**Comment by simonschiller** [comment]
Good point, but we could still use `0` as a default value, which would make it equivalent to `Html.FROM_HTML_MODE_LEGACY`.

**Comment by dovahkiin98** [comment]
The whole 
```Kotlin
Html.fromHtml(String, int)
```
Method is marked only for API > 24

**Comment by simonschiller** [comment]
That's why the `if`-check is in place, the whole purpose of the extension is to deal with the API issue.

**Comment by dovahkiin98** [comment]
Tho if you look at the Html class, the 1 arg method calls the 2 args method

**Comment by avaytsekhovskiy** [comment]
Deprecated method may be removed in future SDK versions. So if you support 19-24 APIs - you have to check and invoke proper method. 

```kotlin
textView.text = rawHtml.fromHtml()
```

**Comment by JakeWharton** [comment]
Maybe `parseAsHtml()`? Calling it "from" usually means you'll be passing something into the function.

**Comment by rom4ek** [comment]
Or just `asHtml()` ?

**Comment by JakeWharton** [comment]
The "as" prefix is mostly used for encapsulation and not conversion/parsing.

**Comment by avaytsekhovskiy** [comment]
Very good point about method naming. I agree with `parseAsHtml()`. 

It is even more clear than native Html.fromHtml()
