### ISSUE TITLE
Request: add easy way to return 0 if collection/array is null

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/android-ktx#324]
Suppose you have this:

    var items: Array<String>? = null
 
I know that instead of this:

    val size: Int = if (items == null) 0 else items!!.size

I can use this:

    val size: Int = items?.size ?: 0

But what I'd like is that since it's so common, let's just have something else:

    val size: Int = items.sizeSafe()

Not sure about the name, but it's important to have the word "size" as the first characters, to make it easier to reach it.
The reason I ask this, is that the first thing you write for returning the size of an array/list, is this way, and not with the special characters.
It's also easier this way to switch between nullable and non-nullable variables.

**Comment by MGaetan89** [comment]
This should rather be suggested to Kotlin stdlib directly, as it is not Android-specific.

**Comment by AndroidDeveloperLB** [comment]
@MGaetan89 Good idea.
Is it possible though to make such an extension function?
I've tried, but failed.

Here are the static functions to do it:

    @JvmStatic
    fun <T> size(array: Array<T>?): Int {
        return array?.size ?: 0
    }

    @JvmStatic
    fun size(collection: Collection<*>?): Int {
        return collection?.size ?: 0
    }

**Comment by AndroidDeveloperLB** [comment]
Another possible improvement: just have `size(defaultValue)` .
Example usage:

    val size: Int = items.size(0)

This means that if the `items` is null, return 0

**Comment by AndroidDeveloperLB** [comment]
OK I wrote about it here:
https://youtrack.jetbrains.com/issue/KT-22835

**Comment by AndroidDeveloperLB** [comment]
Still, could be nice to know how to have it in extension function, if it's even possible

**Comment by MGaetan89** [comment]
You can try something like `fun Array<*>?.sizeSafe() = this?.size ?: 0`

**Comment by AndroidDeveloperLB** [comment]
@MGaetan89 Works great! Thank you !

**Comment by AndroidDeveloperLB** [comment]
So we can use this for example:

    fun Collection<*>?.isEmptySafe() = this?.isEmpty() ?: true
    fun Array<*>?.isEmptySafe() = this?.isEmpty() ?: true
    fun Map<*,*>?.isEmptySafe() = this?.isEmpty() ?: true

    fun Array<*>?.sizeSafe() = this?.size ?: 0
    fun Collection<*>?.sizeSafe() = this?.size ?: 0
    fun Map<*, *>?.sizeSafe() = this?.size ?: 0

Sadly, I will also have to create one for each of the array types (LongArray,SparseArray, ...)
