### ISSUE TITLE
Checking intent extra proposal

### ISSUE THREAD

**Issue by root1991** [android/android-ktx#325]
Sometimes we need to check Intent extra if it exists. So I guess such function can be useful

```
inline fun <reified T> Intent.applyExtra(extra: String, successInvoker: (T) -> Unit, noinline errorInvoker: (() -> Unit)? = null) {
        if (hasExtra(extra)) {
            successInvoker.invoke(extras[extra] as T)
        } else {
            errorInvoker?.invoke()
        }
    }
```

And here is the usage:

```
intent.applyExtra<Int>("layoutID", {
            setContentView(it)
        }, { finish() })

```
What do you think about it? If it can be useful, I'll create PR :)

**Comment by JakeWharton** [comment]
This seems extremely specific. There's probably a hundred APIs that have a has/get pattern and I don't expect us to add this for every single one. Moreover, it prevents more advanced fallback cases where an `else if` would otherwise be used.
