### ISSUE TITLE
Extensions for arch library view model creation

### ISSUE THREAD

**Issue by mattinger** [android/android-ktx#326]
It would be great to add functions to create view models (based on the android arch components).  The syntax is quite verbose due to the ViewModelFactory and generics, which usually requires adding casting and anonymous objects.  Most of the time, you probably want a factory for a single view model type.  With the right inlined functions one could do these with a combination of inline and extension functions.

```
// Standard inline function
viewModelOf(this) { MyViewModel() }

/// Inline extension function
viewModel { MyViewModel() }
```

**Comment by JakeWharton** [comment]
This library only covers the platform. Maybe additional "ktx" libraries will show up in the future though!

**Comment by mattinger** [comment]
I was thinking it might be something like android-ktx-arch (and other library specific extensions)

**Comment by mattinger** [comment]
I've already done this locally, but would have to check with our open source people to see if i can get approval to submit the code.  I also have several things to help with data binding as well.

**Comment by JakeWharton** [comment]
We are not accepting contributions on this repo for anything but the
platform.
