### ISSUE TITLE
Add Database DSL

### ISSUE THREAD

**Issue by printart** [android/android-ktx#328]
This extension adds DSL to SQLiteDatabase:
inline fun `<T>` SQLiteDatabase.dbMake(sqlDb: SQLiteDatabase.() -> T): T {
    return sqlDb(this)
}
Somewhere in your code:
 val result = YourHelper(context).writableDatabase.dbMake {        
    insert()
    update()
    delete()
    query()
 }

**Comment by JakeWharton** [comment]
We already have something like this for transactions: https://android.github.io/android-ktx/core-ktx/androidx.database.sqlite/android.database.sqlite.-s-q-lite-database/index.html

Otherwise this is the same as the standard library's `apply` extension.
