### ISSUE TITLE
Primitive Buffer to ByteArray conversions

### ISSUE THREAD

**Issue by trent-dev** [android/android-ktx#345]
What about something like this for Int/Long/Short?
```
fun IntBuffer.toByteArray(size: Int): ByteArray {
    val byteBuffer = ByteBuffer.allocate(size * 4)
    byteBuffer.asIntBuffer().put(this)
    return byteBuffer.array()
}
```

**Comment by JakeWharton** [comment]
The extensions in this project are only for android.* APIs. You can propose this to JetBrains for inclusion in the Kotlin standard library though.
