### ISSUE TITLE
Get parent Activity from View

### ISSUE THREAD

**Issue by trent-dev** [android/android-ktx#363]
I find this immensely useful when using MVVM pattern.

```
fun View.getActivity(): Activity? {
    var context = context
    while (context is ContextWrapper) {
        if (context is Activity) {
            return context
        }
        context = context.baseContext
    }
    return null
}
```
Please let me know what you think of it. Thanks.

**Comment by JakeWharton** [comment]
I don't think we want to violate the scoping of views with this. Would we also have one for `Dialog`? What about views added directly to `WindowManager` that have neither an `Activity` or `Dialog`? The need to reach outside of your view into the enclosing container should be rare and I'm not sure we want to encourage it at this level.

**Comment by jaredsburrows** [comment]
@trent-dev Are you getting this from the Android code base? Such as `MediaRouteButton`: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/MediaRouteButton.java#163?

**Comment by trent-dev** [comment]
@jaredsburrows Yup. Somewhere similar.

**Comment by hameno** [comment]
We have the following extension in our code:

```
fun Context.getActivityContext(): Activity = when (this) {
    is Activity -> this
    is ContextWrapper -> this.baseContext.getActivityContext()
    else -> throw IllegalArgumentException("Not an activity context")
}
```

I'm not super happy with the IllegalArgumentException but in our case it should never happen.

**Comment by JakeWharton** [comment]
That is needlessly recursive.

I still remain unconvinced we should be promoting this.

**Comment by jaredsburrows** [comment]
@JakeWharton Maybe we can deprecated then prune out this method from `MediaRouteButton`?

**Comment by hameno** [comment]
@JakeWharton Good point, a "tailrec" should fix that, right? I also get your point, it is not always safe to use.

**Comment by JakeWharton** [comment]
It might! Worth a try.

**Comment by JakeWharton** [comment]
Going to close this because we don't want to recommend this as a general pattern. You should very rarely need to do this, but if you do it's fine to keep the code in your codebase only.

**Comment by jaredsburrows** [comment]
@JakeWharton We should make a note to deprecate then remove methods in AOSP.

**Comment by JakeWharton** [comment]
They're not public.

**Comment by jaredsburrows** [comment]
@JakeWharton Good.
