### ISSUE TITLE
Camera 1 Extensions?

### ISSUE THREAD

**Issue by trent-dev** [android/android-ktx#373]
If Camera 1 extension methods are accepted, I'd like to propose some.

This for Camera parameter modification idiom : 
```
fun Camera.setParameters(setAction: (Camera.Parameters) -> Unit) {
    val params = parameters
    setAction(params)
    parameters = params
}
```

This for opening Front / Back cameras :
```
enum class FACING {
    FRONT, BACK
}

fun openCamera(facing: FACING): Camera = Camera.open(getCameraId(facing))

private fun getCameraId(facing: CameraExtensions.FACING): Int {
    val info = Camera.CameraInfo()
    val numCameras = Camera.getNumberOfCameras()
    val direction =
            when (facing) {
                FACING.FRONT -> Camera.CameraInfo.CAMERA_FACING_FRONT
                FACING.BACK -> Camera.CameraInfo.CAMERA_FACING_BACK
            }
    for (i in 0 until numCameras) {
        Camera.getCameraInfo(i, info)
        if (info.facing == direction) {
            return i
        }
    }
    throw RuntimeException("No matching camera for $facing")
}
```
Opinions will be appreciated. Thanks.

**Comment by jaredsburrows** [comment]
Make a PR + tests. See example tests here: https://android.googlesource.com/platform/cts/+/4338156/tests/tests/hardware/src/android/hardware/cts/CameraTest.java.

**Comment by trent-dev** [comment]
@jaredsburrows Thank you for the link. I'll look at it & file a PR soon.

**Comment by romainguy** [comment]
These kind of APIs go beyond the scope of android-ktx extensions and belong to a dedicated library. Thank you for the suggestion though!

**Comment by jaredsburrows** [comment]
@romainguy Maybe `androidx.core:camera-ktx`?
