### ISSUE TITLE
Should updateLayoutParams be on View rather than ViewGroup?

### ISSUE THREAD

**Issue by paulblessing** [android/android-ktx#378]
#371 added `updateLayoutParams` to `ViewGroup`, but I could see this being useful on `View` which is where the `getLayoutParams` and `setLayoutParams` are actually defined. Was there a specific reason it was done for `ViewGroup` only, or just an oversight?

**Comment by romainguy** [comment]
Yup, it should be on `View` indeed.

**Comment by JakeWharton** [comment]
Want to send a PR?
