### ISSUE TITLE
Shorthand to remove view from parent ViewGroup

### ISSUE THREAD

**Issue by Maxr1998** [android/android-ktx#383]
Checks if the parent is a `ViewGroup`, and removes the view from it and returns `true` if successful, and returns `false` if the parent isn't a `ViewGroup` (e.g. it's not set).
Could be modified to be inlined as well.

```Kotlin
fun View.removeFromParent(invalidate: Boolean = true): Boolean {
    if (parent is ViewGroup) {
        val parentView = parent as ViewGroup
        if (invalidate)
            parentView.removeView(this)
        else
            parentView.removeViewInLayout(this)
        return true
    }
    return false
}
```

**Comment by JakeWharton** [comment]
I don't really understand what the use case here is. This seems like a fairly specific requirements rather than something general.

**Comment by JakeWharton** [comment]
This doesn't seem sufficiently general for this library. We already have `minusAssign` allowing `viewGroup -= view` for removing a view. If you're in a layout calling that variant directly seem appropriate. And I'm not sure why you'd need to have this on `View` as it can be trivially checked with a cast and then called with a smart cast.

**Comment by Maxr1998** [comment]
Well, it is somehow useful if you want to remove Views from e.g. your Activity in runtime without bothering about the parent, like:
```Kotlin
findViewById(R.id.xyz).removeFromParent();
```
But I understand what you mean, that use case is probably too specific to be included. I appreciate seeing the -= option though, I didn't know about it.
