### ISSUE TITLE
Feature request - Simplified Android permissions

### ISSUE THREAD

**Issue by rockaport** [android/android-ktx#389]
This is sort of a passthrough to ActivityCompat, but the idea is something along the lines of the following:
```
fun Activity.shouldShowRational(permission: String) = ActivityCompat.shouldShowRequestPermissionRationale(this, permission)

fun Activity.requestPermissions(permissions: Array<String>, requestCode: Int) = ActivityCompat.requestPermissions(this, permissions, requestCode)

```

**Comment by JakeWharton** [comment]
We cannot add these because they would shadow the real functions on `Activity` and thus would be uncallable (Kotlin always prefers calling a member function over an extension).

**Comment by rockaport** [comment]
I derped and named the `requestPermissions` method the same as `Activity.requestPermissions` when copying it over. I have it named as `requestPerms` in one of my repos. I see what you're saying though as it would probably be more confusing if two different methods were shown for requesting permissions.

**Comment by JakeWharton** [comment]
Yes. We're looking into other ways of accomplishing this.
