### ISSUE TITLE
Unity 2017.3.1f1 ARCore App Crashes on Android Phone

### ISSUE THREAD

**Issue by TheAwesomeGuy** [android/android-ktx#396]
I really don't see why... But the app that I developed with Unity's latest version, 2017.3.1f1, crashes on my phone with the new ARCore version of 1.0.180129103. So I am stuck and don't know what to do. I tried every possible angle and I still have crashes.

**Comment by JakeWharton** [comment]
This is not related to the android-ktx library.

**Comment by TheAwesomeGuy** [comment]
Where do I post this then?
