### ISSUE TITLE
Get file from Uri

### ISSUE THREAD

**Issue by Sathawale27** [android/android-ktx#397]
Can we get File from android Uri.
Something like var file = uri.toFile()

**Comment by JakeWharton** [comment]
It exists: https://android.github.io/android-ktx/core-ktx/androidx.os/java.io.-file/to-uri.html

**Comment by Sathawale27** [comment]
Thanks, Jake. It gives a Uri from file. I was looking for File from Uri. Correct me, if i am wrong.

**Comment by JakeWharton** [comment]
Ah, got it. What's the implementation? `new File(getPath())`?

**Comment by Sathawale27** [comment]
Not sure. I guess for external content uri (media images) the implementation is little bit different.

**Comment by JakeWharton** [comment]
You aren't able to get a File for that. The best you can get is a
ParcelFileDescriptor or InputSteam.

**Comment by Sathawale27** [comment]
Ohh, So can we add following:
`inline fun Uri.toFile(): File = File(path)`
