### ISSUE TITLE
String extension for singular and plural 

### ISSUE THREAD

**Issue by vipulasri** [android/android-ktx#411]
An extension function for the string to transform text/string into singular or plural:

`1 day` -> 1 day
`2 day` -> 2 days

`thief` -> thieves
`Knife` -> Knives
`man` -> men

**Comment by JakeWharton** [comment]
You should use [quantity strings][1] for this. Doing it in code breaks localization and the implementation wouldn't be Android specific so it's not appropriate for this project anyway.

 [1]: https://developer.android.com/guide/topics/resources/string-resource.html#Plurals
