### ISSUE TITLE
System services as extension properties

### ISSUE THREAD

**Issue by NikolaDespotoski** [android/android-ktx#424]
Add system services as [extension properties](https://kotlinlang.org/docs/reference/extensions.html#extension-properties) for `Context` receiver.

```
val Context.notificationService: NotificationManager get() = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
val Context.keyguardManager: KeyguardManager get() = getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager
val Context.connectivityManager get() = getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
val Context.powerManager: PowerManager get() = getSystemService(Context.POWER_SERVICE) as PowerManager
```

I wish had more time to cover all system service. It would be great if someone does it.

**Comment by JakeWharton** [comment]
We tried this last year. They would all have to be nullable as any context can return `null` for a service and `null` is often the only indicator that a feature is absent from a particular hardware configuration or permission scenario. It didn't seem worth it compared to `systemService<T>` where you can declare the desired nullability in the type.

**Comment by NikolaDespotoski** [comment]
Just saw the discussion on [Context.systemService<T>](https://github.com/android/android-ktx/issues/282) issue. Thanks.
