### ISSUE TITLE
Put metalava on Google's Maven repo

### ISSUE THREAD

**Issue by jaredsburrows** [android/android-ktx#425]
@tnorbye Could you upload `metalava`(https://android.googlesource.com/platform/tools/metalava/#) to Google's maven repository here: https://dl.google.com/dl/android/maven2/index.html, under `com.android.tools`?

This way we can remove the https://github.com/android/android-ktx/blob/master/update_metalava.sh script and not store a JAR in this repo?

**Comment by tnorbye** [comment]
It's still in pretty active development and there are a bunch of changes coming to hook it up to the support library and framework builds; once that dies down releasing it as a maven library makes a lot of sense.

**Comment by jaredsburrows** [comment]
@tnorbye How can I help? Not even adding snapshots to Google's Maven repo is an option? Or doing `0.x` releases?

**Comment by JakeWharton** [comment]
Closing since it's not related to this project.

**Comment by jaredsburrows** [comment]
@JakeWharton Yeah sorry, I just did not know where else to report it.

**Comment by tnorbye** [comment]
Doing releases on maven.google.com isn't trivial, and I'm not sure I understand why it's so important. I believe Jake came up with some sort of scheme where he's depending on maven artifacts for metalava's largest artifacts (UAST, IntelliJ Core) so the binary snapshots he's checked into androidktx shouldn't be that big.

**Comment by jaredsburrows** [comment]
Yeah. It is more of a convenience factor. So we do not have to "download" it, we should be able to use a POM to make it a transitive dependency and not storing the binary in the with the source code.

**Comment by tnorbye** [comment]
Yep, we'll get there once things settle down.
