### ISSUE TITLE
AnimatorSet repeat method

### ISSUE THREAD

**Issue by trent-dev** [android/android-ktx#429]
`ValueAnimator` has a very useful `repeat` method, while `AnimatorSet` doesn't. This implementation adds such method to `AnimatorSet`.

```
fun AnimatorSet.repeat(times: Int, onDone: (Animator?) -> Unit) {
    var repeatTimes = 0

    addOnDoneListener {
        if (repeatTimes < times) {
            repeatTimes++
            start()
        } else {
            onDone(it)
        }
    }
    start()
}
```

Another implementation which I found particularly useful, given that usually in `AnimatorSet` a lot of different kinds of animations are chained together : 
```
fun AnimatorSet.repeat(times: Int, resetLogic: (Animator?) -> Unit, onDone: (Animator?) -> Unit) {
    var repeatTimes = 0

    addOnDoneListener {
        resetLogic(it)
        if (repeatTimes < times) {
            repeatTimes++
            start()
        } else {
            onDone(it)
        }
    }
    start()
}
```
Let me know what you think of this. Thanks.

**Comment by romainguy** [comment]
Thanks for the suggestion, but this library attempts to only add extensions for existing features, not add new features. This would falls in the second category and is out of scope for the library.
