### ISSUE TITLE
Change Visibility for View using extensionts

### ISSUE THREAD

**Issue by CosminMihuMDC** [android/android-ktx#432]
Implementation suggestion:

Create extension functions for View could be helpful:

```
View.gone()
View.visible()
View.invisible()
```

**Comment by psteiger** [comment]
Hi,

KTX 2.0 already supports something similar:

View.isGone = true
View.isVisible = true
etc

**Comment by JakeWharton** [comment]
Discussion was had in #135 and we added mutable booleans in 0.2.
