### ISSUE TITLE
TextView.setStrikeThrough

### ISSUE THREAD

**Issue by PaulWoitaschek** [android/android-ktx#437]
I have a `TextView` extension for striking or unstriking at text I find quite useful:

```kotlin
import android.graphics.Paint
import android.widget.TextView

fun TextView.setStrikeThrough(strikeThrough: Boolean) {
  paintFlags = if (strikeThrough) {
    paintFlags or Paint.STRIKE_THRU_TEXT_FLAG
  } else {
    paintFlags and Paint.STRIKE_THRU_TEXT_FLAG.inv()
  }
}
```

If accepted I can  do a PR.

**Comment by romainguy** [comment]
There's already an extension for spans: https://github.com/android/android-ktx/blob/master/src/main/java/androidx/core/text/SpannableStringBuilder.kt

It's more generic so I would recommend you use that instead. Thanks for the suggestion though!
