### ISSUE TITLE
updateLayoutParams has wrong receiver type

### ISSUE THREAD

**Issue by LouisCAD** [android/android-ktx#439]
The [`updateLayoutParams { ... } `](https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view-group/update-layout-params.html) extension should have `View` as a receiver, not `ViewGroup`.

The current receiver limits usage on nested `ViewGroup`s.

**Comment by MGaetan89** [comment]
This is already fixed:

https://github.com/android/android-ktx/blob/8de608c8d7cf81f3a637a1b2fcd7992050a567f9/src/main/java/androidx/core/view/View.kt#L265-L288

**Comment by LouisCAD** [comment]
Hope it lands in a 0.2.1 version soon!
