### ISSUE TITLE
bindView delegate

### ISSUE THREAD

**Issue by dovahkiin98** [android/android-ktx#441]
```kotlin
fun <T> Activity.bindView(@IdRes id: Int) = lazy { findViewById<T>(id) }
fun <T> ViewHolder.bindView(@IdRes id: Int) = lazy { itemView.findViewById<T>(id) }

val textView: TextView by bindView(R.id.textView)
```

I know we have kotlin extensions now, but it's not usable in all situations, like when you have a dialog or a viewholder, you can't use kotlin extensions.

**Comment by MGaetan89** [comment]
@dovahkiin98 Android Extensions are going to be more flexible.
It's still experimental for the moment, but you can check the [LayoutContainer](http://kotlinlang.org/docs/tutorials/android-plugin.html#layoutcontainer-support) interface for more information.

**Comment by jaredsburrows** [comment]
@dovahkiin98 Should we consider closing this since it is expensive?

**Comment by Zhuinden** [comment]
> viewholder

Huh? You can use `LayoutContainer` afaik if you add `androidExtensions { experimental = true }`

**Comment by Jawnnypoo** [comment]
@JakeWharton Can you explain how it is expensive? I have used something similar in other projects, so I would want to change it or take it out if this is the case. Is it exactly what @Zhuinden mentioned?

**Comment by Ghedeon** [comment]
As for 'expensiveness', it's doesn't take much to improve:

```kotlin
fun <T : View> View.bind(@IdRes res : Int) : Lazy<T> {
    return lazy(LazyThreadSafetyMode.NONE){ findViewById<T>(res) }
}
```
or something similar to what _kotterknife_ is doing. The interesting concern is if it's going to be encouraged or not. It sets out a pattern that is kinda orthogonal to kotlinx synthetic.

**Comment by JakeWharton** [comment]
Closing as we have no plans to do this. We're not concerned with providing a conflicting strategy with synthetic properties since those are not developed or recommended by the Android team. The concern here is strictly around the overhead of the property delegate for something as simple as view lookup.
