### ISSUE TITLE
Dump contents of Bundle as String

### ISSUE THREAD

**Issue by julioz** [android/android-ktx#459]
Bundle's `toString()` method is as follows:
```
@Override
public synchronized String toString() {
    if (mParcelledData != null) {
        if (isEmptyParcel()) {
            return "Bundle[EMPTY_PARCEL]";
        } else {
            return "Bundle[mParcelledData.dataSize=" +
                    mParcelledData.dataSize() + "]";
        }
    }
    return "Bundle[" + mMap.toString() + "]";
}
```

Which means that reading the contents of the `Bundle` isn't possible when it is parcelled. What do you think of an extension `Bundle -> String` to dump its contents?
Basically iterating through the `keySet()` (this method already `unparcel()`s the `Bundle`) and building a string out of it?

**Comment by JakeWharton** [comment]
There's no Kotlin-specific language features or functional here. Please file your feature request to the support library at https://issuetracker.google.com/issues/new?component=192731
