### ISSUE TITLE
Feature - ScrollView.scrollTo(View)

### ISSUE THREAD

**Issue by Munchery-MaciejPrzybylski** [android/android-ktx#469]
It would be super handy to have this method on scroll containers

ScrollView.scrollTo(v: View)

**Comment by romainguy** [comment]
Thanks for the suggestion but android-ktx doesn't aim to add new features to the platform, rather to take advantage of Kotlin's language feature to make existing APIs easier to use. This sounds like a proposal for AOSP instead.
