### ISSUE TITLE
SharedPreferences putDouble

### ISSUE THREAD

**Issue by Bloody-Badboy** [android/android-ktx#476]
SharedPreferences Extension function to set a double value in the preferences and to retrieve the double value from the preferences

```kotlin
inline fun SharedPreferences.Editor.putDouble(key: String, value: Double): SharedPreferences.Editor {
    putLong(key, value.toRawBits())
    return this
}

inline fun SharedPreferences.getDouble(key: String, defValue: Double) = Double.fromBits(getLong(key, defValue.toRawBits()))
```

**Comment by JakeWharton** [comment]
If this has merit then it seems like something we should just add to the platform. There's nothing special about Kotlin code that makes it such that they should be the only ones that can easily read/write doubles from shared preferences.

**Comment by JakeWharton** [comment]
Please file a feature request for this to be added to the framework at http://b.android.com/new
