### ISSUE TITLE
IntDef 

### ISSUE THREAD

**Issue by Kuloud** [android/android-ktx#482]
As we know, annotation 'IntDef' denotes that the annotated element of integer type, include Int and Long. But when we use the annotation in kotlin, Long const value must be defined, mismatch by Int value. This is inconvenient for porting existing java code.

**Comment by gildor** [comment]
Looks like Support Annotations 27.1 fixed this issue. IntDef now has int value and we also have `@LongDef`
I reported this issue some time ago to Android Issue tracker
https://issuetracker.google.com/issues/37108545

But IntRange (and maybe some other) still have the same problem. I think you should comment issue on Android Issuetracker, this should be changed in Support Library, not new feature of Android KTX
