### ISSUE TITLE
lint warning with sharedpreferences.edit {}

### ISSUE THREAD

**Issue by autonomousapps** [android/android-ktx#486]
This is probably more of a lint issue than an android-ktx issue, but I'm not sure how best to report it.

I'm doing the following:
```
private fun storeDeviceId(context: Context, deviceId: String) {
    getSharedPrefs(context).edit { putString(PREF_DEVICE_ID, deviceId) }
}
```
and it's definitely using the Android KTX extension. However, I get a lint warning that I'm failing to call `commit()` or `apply()`:

![screenshot from 2018-04-03 14-08-35](https://user-images.githubusercontent.com/5402301/38276040-a8eb52be-3748-11e8-98b3-322db1d00394.png)
![screenshot from 2018-04-03 14-08-43](https://user-images.githubusercontent.com/5402301/38276047-ab9e48e0-3748-11e8-9485-af48cc96ed69.png)

**Comment by JakeWharton** [comment]
Yes this is a lint issue and not one of android-ktx itself. And it's already been fixed! https://issuetracker.google.com/issues/74388337
