### ISSUE TITLE
Add subscript and superscript to SpannableStringBuilder.

### ISSUE THREAD

**Issue by jzoran** [android/android-ktx#495]
Superscript and subscript are rather useful for indexing, indicating footnotes, in mathematical notation for exponents and tensor notation etc.

I use them with scale, e.g.
```
val str: SpannedString = buildSpannedString {
    append("x")
    superscript {
        scale(0.75f) {
            append("n")
        }
    }
}
```

It looks like they were omitted by accident (or lack of time). The code would look rather simple using inSpans:

```
  inline fun SpannableStringBuilder.superscript(builderAction: SpannableStringBuilder.() -> Unit) =
    inSpans(SuperscriptSpan(), builderAction = builderAction)
```

PR coming shortly.

**Comment by romainguy** [comment]
Thanks!
