### ISSUE TITLE
Suggesting "View.goneWhen()" function.

### ISSUE THREAD

**Issue by jeonginc** [android/android-ktx#498]
"conditional visibility" is common code especially in RecyclerView.ViewHolder.

here's code.

```
inline fun <V : View> V.goneWhen(predicate: Boolean, visibleAction: V.() -> Unit = {}) {
    if (predicate) {
        visibility = View.GONE
    } else {
        visibility = View.VISIBLE
        visibleAction()
    }
}
```

and usage.

```
list_item_starred.goneWhen(!data.isStarred) {
    clicks().subscribe() {
        unstar(data.id)
    }
}
```

**Comment by hluhovskyi** [comment]
I think it is much clearer to use 
    
    view.isGone = predicate
    if (predicate) {
        doSomething()
    }

It gives exactly same result and makes control flow more straight forward.

**Comment by JakeWharton** [comment]
This isn't a good candidate for this project as it's very specific. It also means we need at least 3 versions of this. In general I don't like the extension as it means that if an `else` is required then you have to completely change the format of the call site from a function/lambda to an if/else.

If this extension is useful to you then it's best to retain it in your project.

Additionally, the example contains something that you probably shouldn't be doing: setting up listeners in onBind and ignoring RxJava `Disposable`s. Bind listeners once when setting up the view holder and then mutate only a reference to the bound item to make onBind allocation-free.
