### ISSUE TITLE
Extension functions to find resource id by name

### ISSUE THREAD

**Issue by denimkqqa** [android/android-ktx#507]
Sometimes it is needed to retrieve drawable, string or other resource id by its name.
So we could make extension functions like this:
```
fun Context.findDrawalbeIdByName(name: String): Int {
    val type = "drawable"
    return getResourceId(name, type)
}

fun Context.findStringIdByName(name: String): Int {
    val type = "string"
    return getResourceId(name, type)

}
....

fun Context.getResourceId(name: String, type: String): Int {
    return resources.getIdentifier(name, type, packageName)
}
```

**Comment by jzoran** [comment]
I'm curious, what is the use case?

Use of getIdentifier is discouraged since it's not really efficient + you already know type and name in R.type.name identifier and should have access to R class from whereever you can also getPackageName() (and if you can't, then you probably shouldn't mess with those resources anyway).

**Comment by consp1racy** [comment]
It's not efficient, it's also the only way to get resources from other packages. But those are only accessible through packageManager.getResourcesForApplication, but that doesn't give you Context. So yeah, what is the use case? 🤔

**Comment by denimkqqa** [comment]
The use case:
- show specific icon (stored locally)  accordingly to the response from the backend

**Comment by consp1racy** [comment]
Thanks for the update.

I don't think the server should know anything about names of your drawables. Having no default method to handle this forces you to make *concious decisions* when you build such extension function *for your particular case*: "Yes, this drawable has coincidentally the same name as a state/label/whatever, so it's safe to get from resource manager, I made it so it works like this."

In other words, the fact that your drawable names correspond to some constants on the server is *your design choice*, specific to your app. If you want an extension function to help you, it should also be specific to your project.

On top of that accessing resources by name is discouraged so I see no point in making this extension function part of standard support library, it's a direct conflict.

Your thoughts?

**Comment by JakeWharton** [comment]
The extensions as proposed are not fit for this library. They don't effectively leverage any Kotlin language feature to improve the interaction. It's just an alias to an existing API on resources.

**Comment by denimkqqa** [comment]
@consp1racy Thanks for reply, that's fair enough.
