### ISSUE TITLE
Add Bitmap.toFile() extension

### ISSUE THREAD

**Issue by Sathawale27** [android/android-ktx#513]
We can create and get file from bitmap.
Something like,

`bitmap.toFile(filePath,compressFormat,quality) : File`

Or 

`bitmap.createFile(filePath,compressFormat,quality) : Boolean`

Returns the result of file creation.

**Comment by romainguy** [comment]
This doesn't really take advantage of Kotlin's language features. It's just a utility wrapper. It's also not as generic as the base `compress` method that can receive an `OutputStream`.
