### ISSUE TITLE
TextView TextWatcher 

### ISSUE THREAD

**Issue by zack-barakat** [android/android-ktx#522]
Similarly to Animator.Kt can we have callback for TextView Listener
Do you think we need to simplify TextWatch implementation to pass actions instead of the whole interface. so we can have something like below.
```
textview.beforeTextChanged { s, start, count, after -> }
textview.onTextChanged { s, start, count, after -> }
textview..afterTextChanged {}
```

**Comment by JakeWharton** [comment]
Text watcher-based listeners have been merged in http://r.android.com/720364

**Comment by PaulWoitaschek** [comment]
And why can't I find them?

**Comment by JakeWharton** [comment]
Probably because you're not using the version they are released in. Or one or a million other problems. You provided zero information so I'm not sure what kind of response you were expecting.

**Comment by poldz123** [comment]
@JakeWharton How does one able to add the updated ktx with widget support dependencies to the gradle? I know it is not in the `1.0.0` since I am using it.

**Comment by jnsnpg** [comment]
I can't find them too
