### ISSUE TITLE
View.layoutParams – Reference assigning to itself

### ISSUE THREAD

**Issue by nil2l** [android/android-ktx#527]
Is this line really needed?
https://github.com/android/android-ktx/blob/3253c2e2cf1a8f85f551d8f71fdec7ed2f36af3e/src/main/java/androidx/core/view/View.kt#L290

```(Kotlin)
inline fun <reified T : ViewGroup.LayoutParams> View.updateLayoutParams(block: T.() -> Unit) {
    val params = layoutParams as T
    // params.equals(this.layoutParams) is true
    block(params)
    // params.equals(this.layoutParams) is still true, so why this assignment?
    layoutParams = params
}
```

**Comment by JakeWharton** [comment]
Yes, it informs the view of the change: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/View.java#15202
