### ISSUE TITLE
[gradle build]error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by huage2580** [android/android-ktx#541]
Error:(251, 5) error: resource android:attr/fontVariationSettings not found.
Error:(251, 5) error: resource android:attr/ttcIndex not found.
 ext.ktx_version='1.0.0-alpha1'
an empty project when add `implementation "androidx.core:core-ktx:$ktx_version"`

i try add this ,but no effect
```java
configurations.all {
    resolutionStrategy.force 'com.android.support:support-v4:27.1.1'
}
```
compileSdkVersion 27 
 buildToolsVersion '27.0.3'
android studio 3.0.1
 classpath 'com.android.tools.build:gradle:3.1.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

**Comment by huage2580** [comment]
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.anko:anko:$anko_version"
    implementation "androidx.core:core-ktx:$ktx_version"
}
 ext.kotlin_version = '1.2.41'
    ext.anko_version='0.10.5'
    ext.ktx_version='1.0.0-alpha1'

**Comment by JakeWharton** [comment]
You cannot mix androidx with support library dependencies. All dependencies must be using androidx dependencies. That error message comes from some transitive collision of attributes, not this project directly.
