### ISSUE TITLE
Add a helper method to set color filters with just a color resource

### ISSUE THREAD

**Issue by dmstocking** [android/android-ktx#545]
This one is minor. But to set a color filter in the code, you have to go get a color int. It was annoying writing it over and over. Basically I am suggesting adding

```
fun ImageView.setColorFilterResource(@ColorRes color: Int) {
    setColorFilter(ContextCompat.getColor(context, color))
}

fun ImageView.setColorFilterResource(@ColorRes color: Int, mode: PorterDuff.Mode) {
    setColorFilter(ContextCompat.getColor(context, color), mode)
}
```

I think this is the right Compat class to handle themes and stuff appropriately, but I could be wrong. That is the second reason I would like this so that I didn't have to worry which Compat class to use.

**Comment by romainguy** [comment]
This doesn't really take advantage of any Kotlin feature beyond being an extension. It would be better in the support library or in the platform itself. android-ktx tries to add extensions that take advantage of Kotlin-specific features to make development easier.

**Comment by dmstocking** [comment]
I would love if this was in support/platform  or android-ktx. I just don't like dealing with it in my projects. I will say that I don't think that argument is very strong though. Literally the first example in the README.md is `myUriString.toUri()` which isn't really doing anything Kotlin specific besides being an extension. I will say that you could argue that this is adding new features to existing APIs.

> It is an explicit goal of this project to not add any new features to the existing Android APIs.

If we didn't want this in android-ktx, then how would I suggest this to the support/platform? I have never done that.

**Comment by JakeWharton** [comment]
Conversion extensions are fairly standard. Since Kotlin rarely (never?) uses static factories on types like Java, extensions and top-level factories are the primary means of conversion between types.

**Comment by romainguy** [comment]
@dmstocking You're right about `toUri`, I should have been clearer in my answer, sorry about that. We do make an exception for conversion extensions like Jake mentioned. We however try to limit them to common types/conversions and not abuse them.

**Comment by dmstocking** [comment]
@romainguy That is fine. Between Jack's explaination that we include ones that just build and the fact that it is kind of adding a new API, I thought I would have to try to get this into "Q" :smile:
