### ISSUE TITLE
Keyboard actions

### ISSUE THREAD

**Issue by PopTudor** [android/android-ktx#547]
Hi, I think it would be really great if we could finally have a standard way & easier API for showing/hiding the keyboard. I can never get it right in the first try and we end up with multiple functions trying to do the same thing but not really working all the time. Also [this question has 3k upvotes and first answer has 4k upvotes](https://stackoverflow.com/questions/1109022/close-hide-the-android-soft-keyboard)

**Comment by JakeWharton** [comment]
Nothing about this sounds Kotlin-specific. General support library requests should be filed on b.android.com/new under the support library component. That being said, the answer to that linked question is looking up a system service for input management and then calling a single method on it which doesn't leave a lot of room for improvement.
