### ISSUE TITLE
AndroidX installation error

### ISSUE THREAD

**Issue by EugW** [android/android-ktx#548]
While using 0.3 all is fine, but when updated to 1.0.0-alpha appeared crash

Android resource linking failed
Output:  D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:470: error: resource android:attr/fontVariationSettings not found.
D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:470: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\wg\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-alpha15-4748712-windows.jar\e01d9e6add059a05309a64e930a6b90b\aapt2-3.2.0-alpha15-4748712-windows\aapt2.exe link -I\
        C:\Users\wg\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        pro.eugw.lessoncountdown\
        -0\
        apk\
        --output-text-symbols\
        D:\wg\Documents\DEV\Projects\LessonCountdown\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha15-4748712-windows Daemon #0

**Comment by JakeWharton** [comment]
core-ktx 1.0.0-alpha1 depends on core 1.0.0-alpha1 which requires compilation against Android P.

https://developer.android.com/reference/android/R.attr#fontVariationSettings

**Comment by zyc945** [comment]
add 
`compileSdkVersion 28`
solve my problem.
