### ISSUE TITLE
create a android template studio

### ISSUE THREAD

**Issue by touseefbsb** [android/android-ktx#552]
I am new to android development so I dont really know where this **suggestion/feature** I was supposed to request, so I am putting it here as this is part of **Jetpack** please redirect me, if this suggestion is supposed to be somewhere else.

**Android Template Studio**

the concept is inspired from **Windows Template Studio** ( https://github.com/Microsoft/WindowsTemplateStudio)

> it will be basically a custom template generator for android projects including best practices baked right in by default.

the user will go through steps in form of a wizard within **android studio** while creating a new **android project** and will select all the items and pages they need for their project, and also select all the services they need, so those services will be baked right in be default in contrast to all pages they need in that app.

**Benefits**

there are many benefits for this, but some of most important are for new developers or even experienced ones who can just startup a project with it and select all the services they need and they will save bulk of time on re inventing the wheel , and they can focus more on their business needs and creative side of the app, hence it will increase productivity massively for every android developer.
Also it can make the new improved stuff in **android development** baked right in by default with best practices, including .
- androidx versioning
- android jetpack services ( all of them or only those can be selected by developer which they need in their app)
- kotlin with kotlin ktx ( and other ktx libraries )
- google play services.

**Example**

**Step 1**

for example I need to create a media player app and for that I open the wizard to create new project and on first step I select my **navigation type** out of some provided options :
1. tabbed
2. side drawer
3. tabbed with floating button
4. side drawer with floating button

>I select **side drawer with floating button**

**Step 2**

on the next page of the wizard I select all the services I need from maybe possible, 20, 30 services which are most commonly used by android apps and are best pratices , are listed there, and I just select a few of them like **media player page**, **background media play**, **suspend state saving**, **sharing contract**, **responsive design for android apps running on chrome OS** and maybe some more.

**Step 3**

now I have listed about 20 kinds of most commonly used pages ( activities/fragements ) and I can select as many of them as I need in my app, and maybe select a single type of page multiple times, and name each of them and then with visual **navigation controller designer** I can make their relation hireirchy right there in the wizard.

> at the end I just name my app and press create, now the android studio will generate the project for me as per instructions I set in the wizard. this will save me all the time, because why should I write code for something that has already been written? instead the wizard can write that code for me with the most basic implementation and best practices already implemented, and with good comments in each code file ( both xml and kt files ) and those comments can tell me the **todo-list** as of what I need to do to change the code to suit to my application so I can just change a couple of lines and then my app is already 60 percent done, now I just need to do my buisiness specific code in there, and I dont have to worry about writing bad code for something or researching for months for a simple task, as if what is the best way to do it, the android community is very big with so much code samples online which is good in a way but also is problematic specially as kotlin is the new language and better one, most samples on web are still in java though.

>so basically to summarize put all the following in one wizard template genrator for the developer, with comment to further docs and best practices.

1. kotlin
2. kotlin-ktx
3. android jetpack ( all services )
4. navigation controller
5. unit testing
6. ui automated testing
7. debugging and performance profiling
8. most popular and recommended plugins by the community

>Please note that all of these services will be available to the developer and they can just pick and choose those services, which they need for their app and they dont need to bulk up the app with unecessary code.  Also the developer will no longer have to do extra research on different places and tutorials to make their app follow best practices in every department of the application, because all of that will be baked in to this template studio.

the idea was inspired from windows template studio which generates the templates in same way for **uwp apps** and it works like a charm, removes a lot of friction for developer. you can do to the link I provided above for WTS and learn more on how this template system works, this will obviously be open source so that community can gather at one place and make one template generating system which is full of best practices and very helpful for all kinds of android developers. Please don't hesitate to ask for any clarifications on this idea, i will be happy to explain more.

**Thanks for reading**

>Also please redirect me if this suggestion should be posted somewhere else.

**Comment by JakeWharton** [comment]
This definitely isn't the correct place for this feature request since this repository is exclusively for core-ktx development only. Your best bet is using the Android Studio template component on the issue tracker: https://issuetracker.google.com/issues/new?component=192760. We don't have any influence or means of producing any of the things requested here.

**Comment by touseefbsb** [comment]
@JakeWharton  thankyou for the redirection :)
