### ISSUE TITLE
merge dex

### ISSUE THREAD

**Issue by raosuj** [android/android-ktx#557]
I am getting below error with ktx_version = "1.0.0-alpha1" when running the app.

`FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForProductionDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex`

I am not seeing this with 0.3.

**Comment by JakeWharton** [comment]
Have you ported your application entirely to androidx package dependencies and enabled jetifier for unmigrated deoendencies?

**Comment by raosuj** [comment]
No, I have not, I am not able to port the entire application as data binding is broken. I want to just use only this. Cant I bring this as standalone

**Comment by JakeWharton** [comment]
No. It is now part of the other JetPack libraries with versioning and dependencies on the androidx components. If you haven't migrated you'll have to stick to 0.3 for now.
