### ISSUE TITLE
I can not sync gradle 

### ISSUE THREAD

**Issue by tvhieuit** [android/android-ktx#561]
<img width="1440" alt="screen shot 2018-05-25 at 6 57 51 pm" src="https://user-images.githubusercontent.com/12293328/40543278-df1a0a32-604d-11e8-92c8-6daaca298edb.png">

**Comment by tvhieuit** [comment]
Im try : android.enableAapt2=false
but got other error: "No resource identifier found for attribute 'appComponentFactory' in package 'android'"

**Comment by danieldaeschle** [comment]
I don't know. Waiting for solution too 😁

**Comment by tvhieuit** [comment]
I had copy some functions used in my project :D

**Comment by danieldaeschle** [comment]
??
I created 2 new clean projects.both doesnt work

**Comment by tvhieuit** [comment]
I just use some func, so I copy that to my project

**Comment by danieldaeschle** [comment]
Which?

**Comment by JakeWharton** [comment]
Dupe of #548. Migrate your project to androidx and compile against Android P if you want to depend on 1.0.
