### ISSUE TITLE
bundleOf() does not support SparseParcelableArray

### ISSUE THREAD

**Issue by nhaarman** [android/android-ktx#563]
Bundle has [putSparseParcelableArray](https://developer.android.com/reference/android/os/Bundle#putSparseParcelableArray(java.lang.String,%20android.util.SparseArray%3C?%20extends%20android.os.Parcelable%3E)), but the `bundleOf()` function does not support this:

```kotlin
bundleOf("foo" to SparseArray<Parcelable>())
```

Error:

```
Caused by: java.lang.IllegalArgumentException: Illegal value type android.util.SparseArray for key "foo"
    at androidx.core.os.BundleKt.bundleOf(Bundle.kt:99)
```

**Comment by JakeWharton** [comment]
Erasure prevents validating the generic type is bound by `Parcelable`. This should be solved by #263 where the call site will change slightly to be fully type-safe.
