### ISSUE TITLE
Int extensions

### ISSUE THREAD

**Issue by heitorzc** [android/android-ktx#564]
Maybe KTX could have some simple extensions for primitive Int. For example:

10.isEven()
11.isOdd()
12.isDivisibleBy(2)
13.isPositive()
-13.isNegative()

Just an idea. ;)
Great work guys! KTX is a piece of heaven!

**Comment by JakeWharton** [comment]
This library is for enhancing types in the android package. These should be proposed to the Kotlin standard library since they are not specific to Android. You can propose them by filing a bug at http://kotl.in/issue
