### ISSUE TITLE
android-ktx supports functional programming?

### ISSUE THREAD

**Issue by touseefbsb** [android/android-ktx#566]
**QUESTION**

as functional programming seems to be the new best practice and kotlin also has strong features to support that by default, I was just wondering whether this library ( **android-ktx** ) is being written and maintain with functional programming in mind?

**Comment by JakeWharton** [comment]
The library is agnostic to programming paradigm. The goal is to adapt the Android framework APIs to the language features of Kotlin. Sometimes that involves functional things. Sometimes it doesn't. The library isn't going to be in the business of excluding one or the other, however.
