### ISSUE TITLE
resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by yizhe25763** [android/android-ktx#572]
error: resource android:attr/fontVariationSettings not found.
Message{kind=ERROR, text=error: resource android:attr/fontVariationSettings not found., sources=[/Users/fanhaoyi/.gradle/wrapper/dists/gradle-3.5-all/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/32cdeb13e776f103732ad7b74a30f04e/res/values/values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

error: resource android:attr/ttcIndex not found.
Message{kind=ERROR, text=error: resource android:attr/ttcIndex not found., sources=[/Users/fanhaoyi/.gradle/wrapper/dists/gradle-3.5-all/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/32cdeb13e776f103732ad7b74a30f04e/res/values/values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

This problem will now occur when a KTX dependency is added after initializing the name。

**Comment by JakeWharton** [comment]
You must compile against API 28.
