### ISSUE TITLE
androidx.preference.PreferenceFragment not derived from androidx.fragment.app.Fragment

### ISSUE THREAD

**Issue by juergenzimmermann** [android/android-ktx#575]
When you have e.g.
```
class Prefs : androidx.preference.PreferenceFragment() {...}
```
then you cannot implement in a Fragment class (derived from androidx.fragment.app.Fragment)
```
fragmentManager?.transaction { replace(R.id.details, Prefs()) }
```
because `replace` expects androidx.fragment.app.Fragment. However, the inheritance hierarchy is Prefs -> androidx.preference.PreferenceFragment -> android.app.Fragment

**Comment by JakeWharton** [comment]
Please file a feature request on b.android.com/new. This isn't a problem with core-ktx, but that the preference androidx library doesn't use androidx fragments.

**Comment by gabrielittner** [comment]
@juergenzimmermann You need to extend `androidx.preference.PreferenceFragmentCompat`.

Here is an issue that requests to deprecate the androidx PreferenceFrament classes that extend platform fragments https://issuetracker.google.com/issues/79405956
