### ISSUE TITLE
Release of 1.0.0-alpha3 out of sync with this repo

### ISSUE THREAD

**Issue by jzoran** [android/android-ktx#577]
alpha3 release seems to be ahead of GitHub repo, e.g. Context.systemService is deprecated. 
alpha2 skipped altogether according to https://dl.google.com/dl/android/maven2/index.html.

You seem to have been working on some internal branch?

**Comment by JakeWharton** [comment]
Yes the source of truth has moved to the main support library repository and this repo is currently a best effort. We pull things in, but synchronizing back out isn't easy or automated and it's not yet clear if it can be made so.

**Comment by jzoran** [comment]
That means it will move to AOSP soon(-ish)?

WIll it then be preferred way of contribution to upload to AOSP Gerrit over GitHub?

**Comment by JakeWharton** [comment]
Whenever androidx 1.0 happens and is pushed to AOSP, yes, you'll see all of the ktx libraries there.

**Comment by JakeWharton** [comment]
The source of truth for core-ktx (and the other KTX libraries) is now in AOSP.
