### ISSUE TITLE
error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by Zedonboy** [android/android-ktx#580]
When ever i add
`implementation 'androidx.core:core-ktx:1.0.0-alpha1'`
i received these errors above
`error: resource android:attr/fontVariationSettings not found.` and `error: resource android:attr/ttcIndex not found.`

here's my gradle
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    // Third Party STuffs
    implementation 'com.google.dagger:dagger-android:2.16'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.16'
    // Kotlin
    implementation 'androidx.core:core-ktx:1.0.0-alpha1'
}`

I dont whats breaking here, What do you suggest?(Thanks In Advance 😄 )

**Comment by JakeWharton** [comment]
As of 1.0.0-alpha-1 all of your support library dependencies must be changed to androidx versions. Also, core-ktx 1.0.0-alpha1 depends on core 1.0.0-alpha1 which requires compilation against Android P.
