### ISSUE TITLE
inline extension properties can't be used in SAM lambda functions due to compiler bug

### ISSUE THREAD

**Issue by technoir42** [android/android-ktx#583]
Kotlin compiler (1.2.50) [crashes](https://youtrack.jetbrains.com/issue/KT-22649) if we use extension property like `View.isVisible` marked `inline` inside a SAM-converted lambda function.
Sample code:
```kotlin
Observable.just(true)
    .subscribe { b ->
        view.isVisible = b
    }
```
Can we remove the `inline` modifier for now until this bug is fixed in the compiler?

**Comment by JakeWharton** [comment]
We can lobby them to fix it in 1.2.60 which will be out before our 1.0.0. I don't really want to change the API, especially in this way, to work around bugs in the Kotlin compiler. We have tens of inline extension properties and there's surely thousands or more across the entire Kotlin library ecosystem and its infeasible to change them all.
