### ISSUE TITLE
Add popular libraries extensions in new module

### ISSUE THREAD

**Issue by LukasAnda** [android/android-ktx#584]
Hi, would it be possible to create separate modules for some popular libraries? Like Retrofit, Glide and so.

Everything should be in its own module because someone would not want to import for example Glide but instead use Picasso.

**Comment by JakeWharton** [comment]
You should evangelize those libraries to ship extensions or port to Kotlin themselves. This project will only be covering the Android platform APIs. Other JetPack libraries already have their own extensions which are developed, versioned, and released with their associated library.
