### ISSUE TITLE
View.post with with this view as a parameter

### ISSUE THREAD

**Issue by romtsn** [android/android-ktx#586]
Sometimes it's tedious to call a `post` method on some `View` object, and then access this object again inside the braces, especially with databinding. For example:

```Kotlin
binding.included.toolbar.post {
    binding.included.toolbar.subtitle = "something"
}
```

If we'd have a following extension, it could make it a little bit easier:
```Kotlin
inline fun <reified T : View> T.postOnView(crossinline action: (T) -> Unit): Runnable

// usage
binding.included.toolbar.postOnView { it.subtitle = "something" }
```

**Comment by JakeWharton** [comment]
My general problem with this is that the majority of APIs accepting some kind of callback or lambda do not provide the enclosing instance and we would have to apply this trick to all of them.

The traditional Kotlin pattern for solving this is to create a scope with the instance you want to re-use with `let`:
```kotlin
binding.included.toolbar.let { toolbar ->
  toolbar.post { toolbar.subtitle = "something" }
}
```

**Comment by rom4ek** [comment]
Good point, also `with` is a good candidate for this. Just thought that the `post` is the most usable thing, which could've had such an extension to ease the usage for those, who is not aware of scoping functions/doesn't want to use them for reasons.
