### ISSUE TITLE
androidx.core.os.BundleKt.bundleOf: Imports for API 21 classes break on older devices

### ISSUE THREAD

**Issue by tellypresence** [android/android-ktx#592]
Suspect that import statements for Size/SizeF (added in API 21) in 
https://github.com/android/android-ktx/blob/master/src/main/java/androidx/core/os/Bundle.kt
are causing problems for older devices; get errors on e.g. Samsung Galaxy 4 (API 19/kitkat 4.4.2):
```
E/dalvikvm: Could not find class 'android.util.Size', referenced from method androidx.core.os.BundleKt.bundleOf
E/dalvikvm: Could not find class 'android.util.SizeF', referenced from method androidx.core.os.BundleKt.bundleOf

```
Maybe replace the imports with fully qualified paths e.g.
**_Before_**
```
import android.util.Size
...
} else if (Build.VERSION.SDK_INT >= 21 && value is Size)

```
**_After_**
```
//import android.util.Size
...
} else if (Build.VERSION.SDK_INT >= 21 && value is android.util.Size)

```

**Comment by JakeWharton** [comment]
Imports have no effect on the bytecode, they're only a construct of source code. Are you just seeing log messages or experiencing an actual crash?

**Comment by stevesamknows** [comment]
After some refactoring and improvements in app code, would say those logs
are safe to ignore; don't think they're causing any actual problems.
