### ISSUE TITLE
gradle error 

### ISSUE THREAD

**Issue by Jparrgam** [android/android-ktx#595]
hi, add android-ktx library in my gradle 

`implementation 'androidx.core:core-ktx:1.0.0-beta01'`

but compiling generates the following error

> Android resource linking failed
Output:  warn: removing resource com.merqueo:string/com_accountkit_button_send_code_in_fb_disclosure without required default value.
/Volumes/Extended/merqueo-app-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:888: error: resource android:attr/fontVariationSettings not found.
/Volumes/Extended/merqueo-app-android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:888: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /Users/jaimeparra/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-beta02-4818971-osx.jar/637ce56c67770e1acb9927afabf2b24e/aapt2-3.2.0-beta02-4818971-osx/aapt2 link -I\
        /Users/jaimeparra/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Volumes/Extended/merqueo-app-android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /Volumes/Extended/merqueo-app-android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Volumes/Extended/merqueo-app-android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Volumes/Extended/merqueo-app-android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --proguard-main-dex\
        /Volumes/Extended/merqueo-app-android/app/build/intermediates/legacy_multidex_aapt_derived_proguard_rules/debug/processDebugResources/manifest_keep.txt\
        --custom-package\
        com.merqueo\
        -0\
        apk\
        --output-text-symbols\
        /Volumes/Extended/merqueo-app-android/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-beta02-4818971-osx Daemon #0

**Comment by JakeWharton** [comment]
core-ktx 1.0.0 depends on core 1.0.0 which requires compilation with API 28.

**Comment by shaishavgandhi05** [comment]
The amount of time this issue has come up makes me wonder if there should be a note somewhere in the readme about compilation against API 28.

**Comment by Jparrgam** [comment]
@JakeWharton  @shaishavgandhi05 
if there should be a note saying that API should be compiled 28
